#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Arms

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_Arms.ABP_Arms_C.AnimBlueprintGeneratedConstantData
// 0x042F (0x0430 - 0x0001)
struct ABP_Arms::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_81;                                 // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlendProfile*                          __BlendProfile_82;                                 // 0x0010(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_83;                                   // 0x0018(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_84;                                 // 0x0020(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_85;                                 // 0x0021(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_86;                                // 0x0028(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_87;                                 // 0x0038(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_88;                                  // 0x0040(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_89;                                 // 0x0044(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_90;                                 // 0x0048(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_91;                                  // 0x0050(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_92;                                // 0x0054(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_93;                               // 0x0058(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_94;                                // 0x0084(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_95;                                 // 0x0088(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_96;                                 // 0x0089(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_97;                                 // 0x008A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8B[0x1];                                       // 0x008B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_98;                                 // 0x008C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_99;                                 // 0x0094(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_100;                                // 0x009C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_101;                                 // 0x00A4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNodeFunctionRef                   __StructProperty_102;                              // 0x00A8(0x0020)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x00C8(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0148(0x0018)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                                // 0x0160(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_CopyPoseFromMesh;                    // 0x0190(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;                     // 0x01C0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone;                          // 0x01F0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace;               // 0x0220(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace;               // 0x0250(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;                  // 0x0280(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;                    // 0x02B0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;                    // 0x02E0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;                       // 0x0310(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;                    // 0x0340(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;                       // 0x0370(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;                      // 0x03A0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;                         // 0x03D0(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;                        // 0x0400(0x0030)()
};
static_assert(alignof(ABP_Arms::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_Arms::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_Arms::FAnimBlueprintGeneratedConstantData) == 0x000430, "Wrong size on ABP_Arms::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_81) == 0x000004, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_81' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __BlendProfile_82) == 0x000010, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__BlendProfile_82' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __CurveFloat_83) == 0x000018, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__CurveFloat_83' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __EnumProperty_84) == 0x000020, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__EnumProperty_84' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __EnumProperty_85) == 0x000021, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__EnumProperty_85' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __ArrayProperty_86) == 0x000028, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__ArrayProperty_86' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_87) == 0x000038, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_87' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __IntProperty_88) == 0x000040, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__IntProperty_88' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __BoolProperty_89) == 0x000044, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__BoolProperty_89' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_90) == 0x000048, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_90' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __IntProperty_91) == 0x000050, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__IntProperty_91' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __FloatProperty_92) == 0x000054, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__FloatProperty_92' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __StructProperty_93) == 0x000058, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__StructProperty_93' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __FloatProperty_94) == 0x000084, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__FloatProperty_94' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __BoolProperty_95) == 0x000088, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__BoolProperty_95' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __EnumProperty_96) == 0x000089, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__EnumProperty_96' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __ByteProperty_97) == 0x00008A, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__ByteProperty_97' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_98) == 0x00008C, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_98' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_99) == 0x000094, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_99' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __NameProperty_100) == 0x00009C, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__NameProperty_100' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __IntProperty_101) == 0x0000A4, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__IntProperty_101' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, __StructProperty_102) == 0x0000A8, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::__StructProperty_102' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0000C8, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000148, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root) == 0x000160, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_CopyPoseFromMesh) == 0x000190, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool) == 0x0001C0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_ModifyBone) == 0x0001F0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LocalToComponentSpace) == 0x000220, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_ComponentToLocalSpace) == 0x000250, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_1) == 0x000280, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult) == 0x0002B0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_2) == 0x0002E0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_2) == 0x000310, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_1) == 0x000340, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_1) == 0x000370, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer) == 0x0003A0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult) == 0x0003D0, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine) == 0x000400, "Member 'ABP_Arms::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine' has a wrong offset!");

// ScriptStruct ABP_Arms.ABP_Arms_C.AnimBlueprintGeneratedMutableData
// 0x0001 (0x0002 - 0x0001)
struct ABP_Arms::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	bool                                          __BoolProperty;                                    // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Arms::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong alignment on ABP_Arms::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ABP_Arms::FAnimBlueprintGeneratedMutableData) == 0x000002, "Wrong size on ABP_Arms::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ABP_Arms::FAnimBlueprintGeneratedMutableData, __BoolProperty) == 0x000001, "Member 'ABP_Arms::FAnimBlueprintGeneratedMutableData::__BoolProperty' has a wrong offset!");

}

