#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LevelTransition_CamMod

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_LevelTransition_CamMod.BP_LevelTransition_CamMod_C.BlueprintModifyPostProcess
// 0x1550 (0x1550 - 0x0000)
struct BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PostProcessBlendWeight;                            // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPostProcessSettings                   PostProcessSettings;                               // 0x0010(0x0700)(Parm, OutParm)
	struct FPostProcessSettings                   NewLocalVar;                                       // 0x0710(0x0700)(Edit, BlueprintVisible)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0E10(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E11[0x3];                                      // 0x0E11(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x0E14(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0E18(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0E19(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1A[0x6];                                      // 0x0E1A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWeightedBlendable                     K2Node_MakeStruct_WeightedBlendable;               // 0x0E20(0x0010)(NoDestructor)
	TArray<struct FWeightedBlendable>             K2Node_MakeArray_Array;                            // 0x0E30(0x0010)(ReferenceParm)
	struct FWeightedBlendables                    K2Node_MakeStruct_WeightedBlendables;              // 0x0E40(0x0010)()
	struct FPostProcessSettings                   K2Node_MakeStruct_PostProcessSettings;             // 0x0E50(0x0700)()
};
static_assert(alignof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess) == 0x000010, "Wrong alignment on BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess");
static_assert(sizeof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess) == 0x001550, "Wrong size on BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, DeltaTime) == 0x000000, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, PostProcessBlendWeight) == 0x000004, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::PostProcessBlendWeight' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, PostProcessSettings) == 0x000010, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::PostProcessSettings' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, NewLocalVar) == 0x000710, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::NewLocalVar' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, CallFunc_IsValid_ReturnValue) == 0x000E10, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, CallFunc_GetFloatValue_ReturnValue) == 0x000E14, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::CallFunc_GetFloatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, CallFunc_IsValid_ReturnValue_1) == 0x000E18, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, CallFunc_BooleanAND_ReturnValue) == 0x000E19, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, K2Node_MakeStruct_WeightedBlendable) == 0x000E20, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::K2Node_MakeStruct_WeightedBlendable' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, K2Node_MakeArray_Array) == 0x000E30, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, K2Node_MakeStruct_WeightedBlendables) == 0x000E40, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::K2Node_MakeStruct_WeightedBlendables' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess, K2Node_MakeStruct_PostProcessSettings) == 0x000E50, "Member 'BP_LevelTransition_CamMod_C_BlueprintModifyPostProcess::K2Node_MakeStruct_PostProcessSettings' has a wrong offset!");

// Function BP_LevelTransition_CamMod.BP_LevelTransition_CamMod_C.ExecuteUbergraph_BP_LevelTransition_CamMod
// 0x0018 (0x0018 - 0x0000)
struct BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerCameraManager*                   K2Node_Event_Camera;                               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod) == 0x000008, "Wrong alignment on BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod");
static_assert(sizeof(BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod) == 0x000018, "Wrong size on BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod");
static_assert(offsetof(BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod, EntryPoint) == 0x000000, "Member 'BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000008, "Member 'BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod, K2Node_Event_Camera) == 0x000010, "Member 'BP_LevelTransition_CamMod_C_ExecuteUbergraph_BP_LevelTransition_CamMod::K2Node_Event_Camera' has a wrong offset!");

// Function BP_LevelTransition_CamMod.BP_LevelTransition_CamMod_C.OnAddedToCamera
// 0x0008 (0x0008 - 0x0000)
struct BP_LevelTransition_CamMod_C_OnAddedToCamera final
{
public:
	class APlayerCameraManager*                   Camera;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_LevelTransition_CamMod_C_OnAddedToCamera) == 0x000008, "Wrong alignment on BP_LevelTransition_CamMod_C_OnAddedToCamera");
static_assert(sizeof(BP_LevelTransition_CamMod_C_OnAddedToCamera) == 0x000008, "Wrong size on BP_LevelTransition_CamMod_C_OnAddedToCamera");
static_assert(offsetof(BP_LevelTransition_CamMod_C_OnAddedToCamera, Camera) == 0x000000, "Member 'BP_LevelTransition_CamMod_C_OnAddedToCamera::Camera' has a wrong offset!");

}

