#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projectile_HeavySpinfusor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Projectile_HeavySpinfusor.BP_Projectile_HeavySpinfusor_C.ExecuteUbergraph_BP_Projectile_HeavySpinfusor
// 0x0004 (0x0004 - 0x0000)
struct BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor) == 0x000004, "Wrong alignment on BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor");
static_assert(sizeof(BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor) == 0x000004, "Wrong size on BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor");
static_assert(offsetof(BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor, EntryPoint) == 0x000000, "Member 'BP_Projectile_HeavySpinfusor_C_ExecuteUbergraph_BP_Projectile_HeavySpinfusor::EntryPoint' has a wrong offset!");

}

