#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Nano_AmplifierBot

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_Nano_AmplifierBot.GA_Nano_AmplifierBot_C.IsAmplified
// 0x0028 (0x0028 - 0x0000)
struct GA_Nano_AmplifierBot_C_IsAmplified final
{
public:
	bool                                          IsAmplified_0;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponentFromActorInfo_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput;    // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Nano_AmplifierBot_C_IsAmplified) == 0x000008, "Wrong alignment on GA_Nano_AmplifierBot_C_IsAmplified");
static_assert(sizeof(GA_Nano_AmplifierBot_C_IsAmplified) == 0x000028, "Wrong size on GA_Nano_AmplifierBot_C_IsAmplified");
static_assert(offsetof(GA_Nano_AmplifierBot_C_IsAmplified, IsAmplified_0) == 0x000000, "Member 'GA_Nano_AmplifierBot_C_IsAmplified::IsAmplified_0' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_IsAmplified, CallFunc_GetAbilitySystemComponentFromActorInfo_ReturnValue) == 0x000008, "Member 'GA_Nano_AmplifierBot_C_IsAmplified::CallFunc_GetAbilitySystemComponentFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_IsAmplified, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000010, "Member 'GA_Nano_AmplifierBot_C_IsAmplified::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_IsAmplified, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000020, "Member 'GA_Nano_AmplifierBot_C_IsAmplified::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");

// Function GA_Nano_AmplifierBot.GA_Nano_AmplifierBot_C.HandleEventActivation
// 0x0018 (0x0018 - 0x0000)
struct GA_Nano_AmplifierBot_C_HandleEventActivation final
{
public:
	class UAbilitySystemComponent*                TargetASC;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UAbilitySystemComponent*>        AffectedASCs;                                      // 0x0008(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GA_Nano_AmplifierBot_C_HandleEventActivation) == 0x000008, "Wrong alignment on GA_Nano_AmplifierBot_C_HandleEventActivation");
static_assert(sizeof(GA_Nano_AmplifierBot_C_HandleEventActivation) == 0x000018, "Wrong size on GA_Nano_AmplifierBot_C_HandleEventActivation");
static_assert(offsetof(GA_Nano_AmplifierBot_C_HandleEventActivation, TargetASC) == 0x000000, "Member 'GA_Nano_AmplifierBot_C_HandleEventActivation::TargetASC' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_HandleEventActivation, AffectedASCs) == 0x000008, "Member 'GA_Nano_AmplifierBot_C_HandleEventActivation::AffectedASCs' has a wrong offset!");

// Function GA_Nano_AmplifierBot.GA_Nano_AmplifierBot_C.ExecuteUbergraph_GA_Nano_AmplifierBot
// 0x0058 (0x0058 - 0x0000)
struct GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTaskOwnerInterface> CallFunc_TaskWaitDelay_TaskOwner_CastInput;        // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UGameplayTask_WaitDelay*                CallFunc_TaskWaitDelay_ReturnValue;                // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAmplified_IsAmplified;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilitySystemComponent*                K2Node_Event_TargetASC;                            // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UAbilitySystemComponent*>        K2Node_Event_AffectedASCs;                         // 0x0040(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	float                                         CallFunc_TaskWaitDelay_Time_ImplicitCast;          // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot) == 0x000008, "Wrong alignment on GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot");
static_assert(sizeof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot) == 0x000058, "Wrong size on GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, EntryPoint) == 0x000000, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, CallFunc_TaskWaitDelay_TaskOwner_CastInput) == 0x000018, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::CallFunc_TaskWaitDelay_TaskOwner_CastInput' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, CallFunc_TaskWaitDelay_ReturnValue) == 0x000028, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::CallFunc_TaskWaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, CallFunc_IsAmplified_IsAmplified) == 0x000030, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::CallFunc_IsAmplified_IsAmplified' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, CallFunc_IsValid_ReturnValue) == 0x000031, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, K2Node_Event_TargetASC) == 0x000038, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::K2Node_Event_TargetASC' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, K2Node_Event_AffectedASCs) == 0x000040, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::K2Node_Event_AffectedASCs' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot, CallFunc_TaskWaitDelay_Time_ImplicitCast) == 0x000050, "Member 'GA_Nano_AmplifierBot_C_ExecuteUbergraph_GA_Nano_AmplifierBot::CallFunc_TaskWaitDelay_Time_ImplicitCast' has a wrong offset!");

// Function GA_Nano_AmplifierBot.GA_Nano_AmplifierBot_C.ApplyEffects
// 0x0080 (0x0080 - 0x0000)
struct GA_Nano_AmplifierBot_C_ApplyEffects final
{
public:
	bool                                          CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectSpecHandle              CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue; // 0x0018(0x0010)()
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectSpecHandle              CallFunc_AssignTagSetByCallerMagnitude_ReturnValue; // 0x0030(0x0010)()
	struct FGameplayEffectSpecHandle              CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1; // 0x0040(0x0010)()
	struct FGameplayEffectSpecHandle              CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_2; // 0x0050(0x0010)()
	struct FActiveGameplayEffectHandle            CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue; // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast; // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_1; // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_2; // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Nano_AmplifierBot_C_ApplyEffects) == 0x000008, "Wrong alignment on GA_Nano_AmplifierBot_C_ApplyEffects");
static_assert(sizeof(GA_Nano_AmplifierBot_C_ApplyEffects) == 0x000080, "Wrong size on GA_Nano_AmplifierBot_C_ApplyEffects");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute) == 0x000000, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue) == 0x000004, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000008, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000010, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue) == 0x000018, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000028, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_ReturnValue) == 0x000030, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1) == 0x000040, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_2) == 0x000050, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue) == 0x000060, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x000068, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast) == 0x000070, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_1) == 0x000074, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(GA_Nano_AmplifierBot_C_ApplyEffects, CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_2) == 0x000078, "Member 'GA_Nano_AmplifierBot_C_ApplyEffects::CallFunc_AssignTagSetByCallerMagnitude_Magnitude_ImplicitCast_2' has a wrong offset!");

}

