#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_OverhealingRestoresShields

#include "Basic.hpp"

#include "GA_OverhealingRestoresShields_classes.hpp"
#include "GA_OverhealingRestoresShields_parameters.hpp"


namespace SDK
{

// Function GA_OverhealingRestoresShields.GA_OverhealingRestoresShields_C.EventOnAbilityRemoved
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FGameplayAbilitySpec             Spec                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_OverhealingRestoresShields_C::EventOnAbilityRemoved(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpec& Spec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverhealingRestoresShields_C", "EventOnAbilityRemoved");

	Params::GA_OverhealingRestoresShields_C_EventOnAbilityRemoved Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Spec = std::move(Spec);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_OverhealingRestoresShields.GA_OverhealingRestoresShields_C.ExecuteUbergraph_GA_OverhealingRestoresShields
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_OverhealingRestoresShields_C::ExecuteUbergraph_GA_OverhealingRestoresShields(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverhealingRestoresShields_C", "ExecuteUbergraph_GA_OverhealingRestoresShields");

	Params::GA_OverhealingRestoresShields_C_ExecuteUbergraph_GA_OverhealingRestoresShields Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_OverhealingRestoresShields.GA_OverhealingRestoresShields_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               EventData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_OverhealingRestoresShields_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverhealingRestoresShields_C", "K2_ActivateAbilityFromEvent");

	Params::GA_OverhealingRestoresShields_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_OverhealingRestoresShields.GA_OverhealingRestoresShields_C.OnHealed
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FHealData                        HealData                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UGA_OverhealingRestoresShields_C::OnHealed(const struct FHealData& HealData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverhealingRestoresShields_C", "OnHealed");

	Params::GA_OverhealingRestoresShields_C_OnHealed Parms{};

	Parms.HealData = std::move(HealData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_OverhealingRestoresShields.GA_OverhealingRestoresShields_C.OnShieldPercentChanged
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_OverhealingRestoresShields_C::OnShieldPercentChanged(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverhealingRestoresShields_C", "OnShieldPercentChanged");

	Params::GA_OverhealingRestoresShields_C_OnShieldPercentChanged Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}

}

