#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Perk_Lightning_Child4

#include "Basic.hpp"

#include "Valhalla_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_Perk_Lightning_Child4.GA_Perk_Lightning_Child4_C.ApplyCritDamageModifier
// 0x0098 (0x0098 - 0x0000)
struct GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier final
{
public:
	float                                         CritDamageMultiplier;                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CritChance;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FValDamageDetail                       DamageDetail;                                      // 0x0008(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FGameplayEffectContextHandle           DamageContext;                                     // 0x0040(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput;    // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableGet_CritDamageMultiplier_ImplicitCast; // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSetRef_Value_ImplicitCast;          // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier) == 0x000008, "Wrong alignment on GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier");
static_assert(sizeof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier) == 0x000098, "Wrong size on GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CritDamageMultiplier) == 0x000000, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CritDamageMultiplier' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CritChance) == 0x000004, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CritChance' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, DamageDetail) == 0x000008, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::DamageDetail' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, DamageContext) == 0x000040, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::DamageContext' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000058, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000068, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000070, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, K2Node_VariableGet_CritDamageMultiplier_ImplicitCast) == 0x000078, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::K2Node_VariableGet_CritDamageMultiplier_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x000080, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x000088, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier, K2Node_VariableSetRef_Value_ImplicitCast) == 0x000090, "Member 'GA_Perk_Lightning_Child4_C_ApplyCritDamageModifier::K2Node_VariableSetRef_Value_ImplicitCast' has a wrong offset!");

}

