#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_RL_ElementalDamageSynergy_Base

#include "Basic.hpp"

#include "GA_RL_ElementalDamageSynergy_Base_classes.hpp"
#include "GA_RL_ElementalDamageSynergy_Base_parameters.hpp"


namespace SDK
{

// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.Has Other Element Debuff Tag
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilitySystemComponent*          ASC                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     InDebuffTag                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    HasTag                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     OutDebuffTag                                           (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void UGA_RL_ElementalDamageSynergy_Base_C::Has_Other_Element_Debuff_Tag(class UAbilitySystemComponent* ASC, const struct FGameplayTag& InDebuffTag, bool* HasTag, struct FGameplayTag* OutDebuffTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "Has Other Element Debuff Tag");

	Params::GA_RL_ElementalDamageSynergy_Base_C_Has_Other_Element_Debuff_Tag Parms{};

	Parms.ASC = ASC;
	Parms.InDebuffTag = std::move(InDebuffTag);

	UObject::ProcessEvent(Func, &Parms);

	if (HasTag != nullptr)
		*HasTag = Parms.HasTag;

	if (OutDebuffTag != nullptr)
		*OutDebuffTag = std::move(Parms.OutDebuffTag);
}


// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.ApplyDamageOutputModifier
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   OutPercentModifier                                     (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutFlatModifier                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayEffectContextHandle     DamageContext                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FGameplayEffectSpec              DamageSpec                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FValDamageDetail                 DamageDetail                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void UGA_RL_ElementalDamageSynergy_Base_C::ApplyDamageOutputModifier(float& OutPercentModifier, float& OutFlatModifier, float Damage, const struct FGameplayEffectContextHandle& DamageContext, const struct FGameplayEffectSpec& DamageSpec, const struct FValDamageDetail& DamageDetail)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "ApplyDamageOutputModifier");

	Params::GA_RL_ElementalDamageSynergy_Base_C_ApplyDamageOutputModifier Parms{};

	Parms.OutPercentModifier = OutPercentModifier;
	Parms.OutFlatModifier = OutFlatModifier;
	Parms.Damage = Damage;
	Parms.DamageContext = std::move(DamageContext);
	Parms.DamageSpec = std::move(DamageSpec);
	Parms.DamageDetail = std::move(DamageDetail);

	UObject::ProcessEvent(Func, &Parms);

	OutPercentModifier = Parms.OutPercentModifier;
	OutFlatModifier = Parms.OutFlatModifier;
}


// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.ApplyEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UValAbilitySystemComponent*       TargetASC                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     ElementalDebuffTag                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     ElementalDamageTag                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGA_RL_ElementalDamageSynergy_Base_C::ApplyEffect(class UValAbilitySystemComponent* TargetASC, const struct FGameplayTag& ElementalDebuffTag, const struct FGameplayTag& ElementalDamageTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "ApplyEffect");

	Params::GA_RL_ElementalDamageSynergy_Base_C_ApplyEffect Parms{};

	Parms.TargetASC = TargetASC;
	Parms.ElementalDebuffTag = std::move(ElementalDebuffTag);
	Parms.ElementalDamageTag = std::move(ElementalDamageTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.BeginPlay
// (Event, Public, BlueprintEvent)

void UGA_RL_ElementalDamageSynergy_Base_C::BeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "BeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.OnDealtDamage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageData                      Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_RL_ElementalDamageSynergy_Base_C::OnDealtDamage(const struct FDamageData& Data, class AActor* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "OnDealtDamage");

	Params::GA_RL_ElementalDamageSynergy_Base_C_OnDealtDamage Parms{};

	Parms.Data = std::move(Data);
	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RL_ElementalDamageSynergy_Base.GA_RL_ElementalDamageSynergy_Base_C.ExecuteUbergraph_GA_RL_ElementalDamageSynergy_Base
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RL_ElementalDamageSynergy_Base_C::ExecuteUbergraph_GA_RL_ElementalDamageSynergy_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_ElementalDamageSynergy_Base_C", "ExecuteUbergraph_GA_RL_ElementalDamageSynergy_Base");

	Params::GA_RL_ElementalDamageSynergy_Base_C_ExecuteUbergraph_GA_RL_ElementalDamageSynergy_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

