#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_RL_SwapGrantsSpeedAndDodge

#include "Basic.hpp"

#include "GA_RL_SwapGrantsSpeedAndDodge_classes.hpp"
#include "GA_RL_SwapGrantsSpeedAndDodge_parameters.hpp"


namespace SDK
{

// Function GA_RL_SwapGrantsSpeedAndDodge.GA_RL_SwapGrantsSpeedAndDodge_C.EventOnAbilityGiven
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FGameplayAbilitySpec             Spec                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_RL_SwapGrantsSpeedAndDodge_C::EventOnAbilityGiven(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpec& Spec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_SwapGrantsSpeedAndDodge_C", "EventOnAbilityGiven");

	Params::GA_RL_SwapGrantsSpeedAndDodge_C_EventOnAbilityGiven Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Spec = std::move(Spec);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RL_SwapGrantsSpeedAndDodge.GA_RL_SwapGrantsSpeedAndDodge_C.EventOnAbilityRemoved
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FGameplayAbilitySpec             Spec                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_RL_SwapGrantsSpeedAndDodge_C::EventOnAbilityRemoved(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpec& Spec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_SwapGrantsSpeedAndDodge_C", "EventOnAbilityRemoved");

	Params::GA_RL_SwapGrantsSpeedAndDodge_C_EventOnAbilityRemoved Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Spec = std::move(Spec);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RL_SwapGrantsSpeedAndDodge.GA_RL_SwapGrantsSpeedAndDodge_C.ExecuteUbergraph_GA_RL_SwapGrantsSpeedAndDodge
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_RL_SwapGrantsSpeedAndDodge_C::ExecuteUbergraph_GA_RL_SwapGrantsSpeedAndDodge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_SwapGrantsSpeedAndDodge_C", "ExecuteUbergraph_GA_RL_SwapGrantsSpeedAndDodge");

	Params::GA_RL_SwapGrantsSpeedAndDodge_C_ExecuteUbergraph_GA_RL_SwapGrantsSpeedAndDodge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_RL_SwapGrantsSpeedAndDodge.GA_RL_SwapGrantsSpeedAndDodge_C.OnSwapped
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     GameplayTag                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_RL_SwapGrantsSpeedAndDodge_C::OnSwapped(const struct FGameplayTag& GameplayTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_RL_SwapGrantsSpeedAndDodge_C", "OnSwapped");

	Params::GA_RL_SwapGrantsSpeedAndDodge_C_OnSwapped Parms{};

	Parms.GameplayTag = std::move(GameplayTag);

	UObject::ProcessEvent(Func, &Parms);
}

}

