#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_SmartRocket_Grenade

#include "Basic.hpp"

#include "GA_SmartRocket_Grenade_classes.hpp"
#include "GA_SmartRocket_Grenade_parameters.hpp"


namespace SDK
{

// Function GA_SmartRocket_Grenade.GA_SmartRocket_Grenade_C.ExecuteUbergraph_GA_SmartRocket_Grenade
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SmartRocket_Grenade_C::ExecuteUbergraph_GA_SmartRocket_Grenade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SmartRocket_Grenade_C", "ExecuteUbergraph_GA_SmartRocket_Grenade");

	Params::GA_SmartRocket_Grenade_C_ExecuteUbergraph_GA_SmartRocket_Grenade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SmartRocket_Grenade.GA_SmartRocket_Grenade_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_SmartRocket_Grenade_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SmartRocket_Grenade_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SmartRocket_Grenade.GA_SmartRocket_Grenade_C.OnEquipSlotsUpdated
// (BlueprintCallable, BlueprintEvent)

void UGA_SmartRocket_Grenade_C::OnEquipSlotsUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SmartRocket_Grenade_C", "OnEquipSlotsUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_SmartRocket_Grenade.GA_SmartRocket_Grenade_C.OnExplode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Projectile_Grenade_Master_C*  Grenade                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_SmartRocket_Grenade_C::OnExplode(class ABP_Projectile_Grenade_Master_C* Grenade)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SmartRocket_Grenade_C", "OnExplode");

	Params::GA_SmartRocket_Grenade_C_OnExplode Parms{};

	Parms.Grenade = Grenade;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_SmartRocket_Grenade.GA_SmartRocket_Grenade_C.SpawnSecondaryGrenade
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform                       Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_SmartRocket_Grenade_C::SpawnSecondaryGrenade(const struct FTransform& Transform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_SmartRocket_Grenade_C", "SpawnSecondaryGrenade");

	Params::GA_SmartRocket_Grenade_C_SpawnSecondaryGrenade Parms{};

	Parms.Transform = std::move(Transform);

	UObject::ProcessEvent(Func, &Parms);
}

}

