#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ShortRange_Base

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_ShortRange_Base.GA_ShortRange_Base_C.ApplyDamageResistanceModifier
// 0x0068 (0x0068 - 0x0000)
struct GA_ShortRange_Base_C_ApplyDamageResistanceModifier final
{
public:
	float                                         OutPercentModifier;                                // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OutFlatModifier;                                   // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OutShieldModifier;                                 // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           DamageContext;                                     // 0x0010(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	int32                                         CallFunc_GetNearbyEnemyCount_Count;                // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMin_ReturnValue;                         // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableGet_OutPercentModifier_ImplicitCast; // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_VariableSetRef_Target_ImplicitCast;         // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier) == 0x000008, "Wrong alignment on GA_ShortRange_Base_C_ApplyDamageResistanceModifier");
static_assert(sizeof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier) == 0x000068, "Wrong size on GA_ShortRange_Base_C_ApplyDamageResistanceModifier");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, OutPercentModifier) == 0x000000, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::OutPercentModifier' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, OutFlatModifier) == 0x000004, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::OutFlatModifier' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, OutShieldModifier) == 0x000008, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::OutShieldModifier' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, Damage) == 0x00000C, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::Damage' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, DamageContext) == 0x000010, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::DamageContext' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_GetNearbyEnemyCount_Count) == 0x000028, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_GetNearbyEnemyCount_Count' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000030, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000038, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_FMin_ReturnValue) == 0x000040, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000048, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, K2Node_VariableGet_OutPercentModifier_ImplicitCast) == 0x000050, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::K2Node_VariableGet_OutPercentModifier_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, K2Node_VariableSetRef_Target_ImplicitCast) == 0x000058, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::K2Node_VariableSetRef_Target_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ApplyDamageResistanceModifier, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x000060, "Member 'GA_ShortRange_Base_C_ApplyDamageResistanceModifier::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function GA_ShortRange_Base.GA_ShortRange_Base_C.ExecuteUbergraph_GA_ShortRange_Base
// 0x0040 (0x0040 - 0x0000)
struct GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AValGameState*                          K2Node_DynamicCast_AsVal_Game_State;               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_HasAuthority_ReturnValue;              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AValCharacter*                          K2Node_DynamicCast_AsVal_Character;                // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base) == 0x000008, "Wrong alignment on GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base");
static_assert(sizeof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base) == 0x000040, "Wrong size on GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, EntryPoint) == 0x000000, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, CallFunc_GetGameState_ReturnValue) == 0x000008, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, K2Node_DynamicCast_AsVal_Game_State) == 0x000010, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::K2Node_DynamicCast_AsVal_Game_State' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x000020, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, CallFunc_K2_HasAuthority_ReturnValue) == 0x000028, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::CallFunc_K2_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, K2Node_DynamicCast_AsVal_Character) == 0x000030, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::K2Node_DynamicCast_AsVal_Character' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'GA_ShortRange_Base_C_ExecuteUbergraph_GA_ShortRange_Base::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function GA_ShortRange_Base.GA_ShortRange_Base_C.GetMultiplierValueForTarget
// 0x0060 (0x0060 - 0x0000)
struct GA_ShortRange_Base_C_GetMultiplierValueForTarget final
{
public:
	class AActor*                                 Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Multiplier;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Decay;                                             // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Value;                                             // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_ReturnValue;                         // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_ReturnValue_1;                       // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_ShortRange_Base_C_GetMultiplierValueForTarget) == 0x000008, "Wrong alignment on GA_ShortRange_Base_C_GetMultiplierValueForTarget");
static_assert(sizeof(GA_ShortRange_Base_C_GetMultiplierValueForTarget) == 0x000060, "Wrong size on GA_ShortRange_Base_C_GetMultiplierValueForTarget");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, Target) == 0x000000, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::Target' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, Multiplier) == 0x000008, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::Multiplier' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, Decay) == 0x000010, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::Decay' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, Value) == 0x000018, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::Value' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_GetDistanceTo_ReturnValue) == 0x000020, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000028, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_FMax_ReturnValue) == 0x000030, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000038, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000040, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000048, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_FMax_ReturnValue_1) == 0x000050, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_FMax_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetMultiplierValueForTarget, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x000058, "Member 'GA_ShortRange_Base_C_GetMultiplierValueForTarget::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function GA_ShortRange_Base.GA_ShortRange_Base_C.GetNearbyEnemyCount
// 0x00C8 (0x00C8 - 0x0000)
struct GA_ShortRange_Base_C_GetNearbyEnemyCount final
{
public:
	int32                                         Count;                                             // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LocalNearbyCount;                                  // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AValAIController*>               CallFunc_GetAllAIControllers_AIControllers;        // 0x0018(0x0010)(ReferenceParm)
	TArray<class AValAIController*>               CallFunc_GetCachedArray_ReturnValue;               // 0x0028(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AValAIController*                       CallFunc_Array_Get_Item;                           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AValCharacter*                          CallFunc_GetValCharacter_ReturnValue;              // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEnemyWith_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IValDamageable>        CallFunc_IsAlive_self_CastInput;                   // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAlive_ReturnValue;                      // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_DistanceSquared_ReturnValue;       // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Square_ReturnValue;                       // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_ShortRange_Base_C_GetNearbyEnemyCount) == 0x000008, "Wrong alignment on GA_ShortRange_Base_C_GetNearbyEnemyCount");
static_assert(sizeof(GA_ShortRange_Base_C_GetNearbyEnemyCount) == 0x0000C8, "Wrong size on GA_ShortRange_Base_C_GetNearbyEnemyCount");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, Count) == 0x000000, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::Count' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, LocalNearbyCount) == 0x000004, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::LocalNearbyCount' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, Temp_int_Array_Index_Variable) == 0x000010, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, Temp_int_Variable) == 0x000014, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_GetAllAIControllers_AIControllers) == 0x000018, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_GetAllAIControllers_AIControllers' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_GetCachedArray_ReturnValue) == 0x000028, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_GetCachedArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Add_IntInt_ReturnValue_1) == 0x000038, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Array_Get_Item) == 0x000040, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_GetValCharacter_ReturnValue) == 0x000048, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_GetValCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_IsEnemyWith_ReturnValue) == 0x000050, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_IsEnemyWith_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000058, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_IsValid_ReturnValue) == 0x000070, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_IsAlive_self_CastInput) == 0x000078, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_IsAlive_self_CastInput' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_IsAlive_ReturnValue) == 0x000088, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_IsAlive_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Array_Length_ReturnValue) == 0x00008C, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Less_IntInt_ReturnValue) == 0x000090, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000098, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Vector_DistanceSquared_ReturnValue) == 0x0000B0, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Vector_DistanceSquared_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_Square_ReturnValue) == 0x0000B8, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_Square_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_ShortRange_Base_C_GetNearbyEnemyCount, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x0000C0, "Member 'GA_ShortRange_Base_C_GetNearbyEnemyCount::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");

}

