#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Turret_Weapon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Gun_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Turret_Weapon.GA_Turret_Weapon_C
// 0x0008 (0x0930 - 0x0928)
class UGA_Turret_Weapon_C final : public UGA_Gun_Master_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Turret_Weapon_C;                 // 0x0928(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Turret_Weapon(int32 EntryPoint);
	void K2_ActivateAbility();

	bool ValCheckCost(const struct FGameplayAbilitySpecHandle& Handle, const struct FGameplayAbilityActorInfo& ActorInfo) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Turret_Weapon_C">();
	}
	static class UGA_Turret_Weapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Turret_Weapon_C>();
	}
};
static_assert(alignof(UGA_Turret_Weapon_C) == 0x000008, "Wrong alignment on UGA_Turret_Weapon_C");
static_assert(sizeof(UGA_Turret_Weapon_C) == 0x000930, "Wrong size on UGA_Turret_Weapon_C");
static_assert(offsetof(UGA_Turret_Weapon_C, UberGraphFrame_GA_Turret_Weapon_C) == 0x000928, "Member 'UGA_Turret_Weapon_C::UberGraphFrame_GA_Turret_Weapon_C' has a wrong offset!");

}

