#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_AOEShield

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GC_AOEShield.GC_AOEShield_C.OnExecute
// 0x00E8 (0x00E8 - 0x0000)
struct GC_AOEShield_C_OnExecute final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_AOEShield_C_OnExecute) == 0x000008, "Wrong alignment on GC_AOEShield_C_OnExecute");
static_assert(sizeof(GC_AOEShield_C_OnExecute) == 0x0000E8, "Wrong size on GC_AOEShield_C_OnExecute");
static_assert(offsetof(GC_AOEShield_C_OnExecute, MyTarget) == 0x000000, "Member 'GC_AOEShield_C_OnExecute::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_OnExecute, Parameters) == 0x000008, "Member 'GC_AOEShield_C_OnExecute::Parameters' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_OnExecute, ReturnValue) == 0x0000E0, "Member 'GC_AOEShield_C_OnExecute::ReturnValue' has a wrong offset!");

// Function GC_AOEShield.GC_AOEShield_C.OnRemove
// 0x00E8 (0x00E8 - 0x0000)
struct GC_AOEShield_C_OnRemove final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_AOEShield_C_OnRemove) == 0x000008, "Wrong alignment on GC_AOEShield_C_OnRemove");
static_assert(sizeof(GC_AOEShield_C_OnRemove) == 0x0000E8, "Wrong size on GC_AOEShield_C_OnRemove");
static_assert(offsetof(GC_AOEShield_C_OnRemove, MyTarget) == 0x000000, "Member 'GC_AOEShield_C_OnRemove::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_OnRemove, Parameters) == 0x000008, "Member 'GC_AOEShield_C_OnRemove::Parameters' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_OnRemove, ReturnValue) == 0x0000E0, "Member 'GC_AOEShield_C_OnRemove::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_OnRemove, CallFunc_IsValid_ReturnValue) == 0x0000E1, "Member 'GC_AOEShield_C_OnRemove::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function GC_AOEShield.GC_AOEShield_C.WhileActive
// 0x0100 (0x0100 - 0x0000)
struct GC_AOEShield_C_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AValCharacter*                          K2Node_DynamicCast_AsVal_Character;                // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_SpawnSystemAttached_ReturnValue;          // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_AOEShield_C_WhileActive) == 0x000008, "Wrong alignment on GC_AOEShield_C_WhileActive");
static_assert(sizeof(GC_AOEShield_C_WhileActive) == 0x000100, "Wrong size on GC_AOEShield_C_WhileActive");
static_assert(offsetof(GC_AOEShield_C_WhileActive, MyTarget) == 0x000000, "Member 'GC_AOEShield_C_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_WhileActive, Parameters) == 0x000008, "Member 'GC_AOEShield_C_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_WhileActive, ReturnValue) == 0x0000E0, "Member 'GC_AOEShield_C_WhileActive::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_WhileActive, K2Node_DynamicCast_AsVal_Character) == 0x0000E8, "Member 'GC_AOEShield_C_WhileActive::K2Node_DynamicCast_AsVal_Character' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_WhileActive, K2Node_DynamicCast_bSuccess) == 0x0000F0, "Member 'GC_AOEShield_C_WhileActive::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_AOEShield_C_WhileActive, CallFunc_SpawnSystemAttached_ReturnValue) == 0x0000F8, "Member 'GC_AOEShield_C_WhileActive::CallFunc_SpawnSystemAttached_ReturnValue' has a wrong offset!");

}

