#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_HealthRegen

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GC_HealthRegen.GC_HealthRegen_C.DespawnFX
// 0x0038 (0x0038 - 0x0000)
struct GC_HealthRegen_C_DespawnFX final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CharPlayer_C*                       K2Node_DynamicCast_AsBP_Char_Player;               // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_Create_1P3P_VFX_Active_1PVFX;             // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_Create_1P3P_VFX_1P_System_Ref;            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_Create_1P3P_VFX_Active_3PVFX;             // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_Create_1P3P_VFX_3P_System_Ref;            // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_DespawnFX) == 0x000008, "Wrong alignment on GC_HealthRegen_C_DespawnFX");
static_assert(sizeof(GC_HealthRegen_C_DespawnFX) == 0x000038, "Wrong size on GC_HealthRegen_C_DespawnFX");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, ReturnValue) == 0x000000, "Member 'GC_HealthRegen_C_DespawnFX::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_IsValid_ReturnValue_1) == 0x000002, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, K2Node_DynamicCast_AsBP_Char_Player) == 0x000008, "Member 'GC_HealthRegen_C_DespawnFX::K2Node_DynamicCast_AsBP_Char_Player' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'GC_HealthRegen_C_DespawnFX::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_IsValid_ReturnValue_2) == 0x000011, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_Create_1P3P_VFX_Active_1PVFX) == 0x000018, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_Create_1P3P_VFX_Active_1PVFX' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_Create_1P3P_VFX_1P_System_Ref) == 0x000020, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_Create_1P3P_VFX_1P_System_Ref' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_Create_1P3P_VFX_Active_3PVFX) == 0x000028, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_Create_1P3P_VFX_Active_3PVFX' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_DespawnFX, CallFunc_Create_1P3P_VFX_3P_System_Ref) == 0x000030, "Member 'GC_HealthRegen_C_DespawnFX::CallFunc_Create_1P3P_VFX_3P_System_Ref' has a wrong offset!");

// Function GC_HealthRegen.GC_HealthRegen_C.OnActive
// 0x00E8 (0x00E8 - 0x0000)
struct GC_HealthRegen_C_OnActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_OnActive) == 0x000008, "Wrong alignment on GC_HealthRegen_C_OnActive");
static_assert(sizeof(GC_HealthRegen_C_OnActive) == 0x0000E8, "Wrong size on GC_HealthRegen_C_OnActive");
static_assert(offsetof(GC_HealthRegen_C_OnActive, MyTarget) == 0x000000, "Member 'GC_HealthRegen_C_OnActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnActive, Parameters) == 0x000008, "Member 'GC_HealthRegen_C_OnActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnActive, ReturnValue) == 0x0000E0, "Member 'GC_HealthRegen_C_OnActive::ReturnValue' has a wrong offset!");

// Function GC_HealthRegen.GC_HealthRegen_C.OnRemove
// 0x0100 (0x0100 - 0x0000)
struct GC_HealthRegen_C_OnRemove final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00E4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00F6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F7[0x1];                                       // 0x00F7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_SpawnSystemAttached_ReturnValue;          // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_OnRemove) == 0x000008, "Wrong alignment on GC_HealthRegen_C_OnRemove");
static_assert(sizeof(GC_HealthRegen_C_OnRemove) == 0x000100, "Wrong size on GC_HealthRegen_C_OnRemove");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, MyTarget) == 0x000000, "Member 'GC_HealthRegen_C_OnRemove::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, Parameters) == 0x000008, "Member 'GC_HealthRegen_C_OnRemove::Parameters' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, ReturnValue) == 0x0000E0, "Member 'GC_HealthRegen_C_OnRemove::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, K2Node_CreateDelegate_OutputDelegate) == 0x0000E4, "Member 'GC_HealthRegen_C_OnRemove::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, CallFunc_IsValid_ReturnValue) == 0x0000F4, "Member 'GC_HealthRegen_C_OnRemove::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, CallFunc_IsValid_ReturnValue_1) == 0x0000F5, "Member 'GC_HealthRegen_C_OnRemove::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, CallFunc_IsValid_ReturnValue_2) == 0x0000F6, "Member 'GC_HealthRegen_C_OnRemove::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnRemove, CallFunc_SpawnSystemAttached_ReturnValue) == 0x0000F8, "Member 'GC_HealthRegen_C_OnRemove::CallFunc_SpawnSystemAttached_ReturnValue' has a wrong offset!");

// Function GC_HealthRegen.GC_HealthRegen_C.OnViewTargetChanged
// 0x0010 (0x0010 - 0x0000)
struct GC_HealthRegen_C_OnViewTargetChanged final
{
public:
	class AActor*                                 NewViewTarget;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DespawnFX_ReturnValue;                    // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_OnViewTargetChanged) == 0x000008, "Wrong alignment on GC_HealthRegen_C_OnViewTargetChanged");
static_assert(sizeof(GC_HealthRegen_C_OnViewTargetChanged) == 0x000010, "Wrong size on GC_HealthRegen_C_OnViewTargetChanged");
static_assert(offsetof(GC_HealthRegen_C_OnViewTargetChanged, NewViewTarget) == 0x000000, "Member 'GC_HealthRegen_C_OnViewTargetChanged::NewViewTarget' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_OnViewTargetChanged, CallFunc_DespawnFX_ReturnValue) == 0x000008, "Member 'GC_HealthRegen_C_OnViewTargetChanged::CallFunc_DespawnFX_ReturnValue' has a wrong offset!");

// Function GC_HealthRegen.GC_HealthRegen_C.ToggleVFX
// 0x0038 (0x0038 - 0x0000)
struct GC_HealthRegen_C_ToggleVFX final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponent_ReturnValue;    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput;    // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_Update_1P3P_VFX_Active_1P;                // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_Update_1P3P_VFX_Active_3P;                // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_ToggleVFX) == 0x000008, "Wrong alignment on GC_HealthRegen_C_ToggleVFX");
static_assert(sizeof(GC_HealthRegen_C_ToggleVFX) == 0x000038, "Wrong size on GC_HealthRegen_C_ToggleVFX");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_GetAbilitySystemComponent_ReturnValue) == 0x000008, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_GetAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000010, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000020, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_Update_1P3P_VFX_Active_1P) == 0x000028, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_Update_1P3P_VFX_Active_1P' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_ToggleVFX, CallFunc_Update_1P3P_VFX_Active_3P) == 0x000030, "Member 'GC_HealthRegen_C_ToggleVFX::CallFunc_Update_1P3P_VFX_Active_3P' has a wrong offset!");

// Function GC_HealthRegen.GC_HealthRegen_C.WhileActive
// 0x0170 (0x0170 - 0x0000)
struct GC_HealthRegen_C_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CharPlayer_C*                       K2Node_DynamicCast_AsBP_Char_Player;               // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AValCharacter*                          K2Node_DynamicCast_AsVal_Character;                // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 CallFunc_GetMesh1P_ReturnValue;                    // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_GetMesh3P_ReturnValue;                    // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AValPlayerController*                   K2Node_DynamicCast_AsVal_Player_Controller;        // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x012C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AActor* NewViewTarget)>  K2Node_CreateDelegate_OutputDelegate_1;            // 0x013C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_Create_1P3P_VFX_Active_1PVFX;             // 0x0150(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_Create_1P3P_VFX_1P_System_Ref;            // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_Create_1P3P_VFX_Active_3PVFX;             // 0x0160(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_Create_1P3P_VFX_3P_System_Ref;            // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_HealthRegen_C_WhileActive) == 0x000008, "Wrong alignment on GC_HealthRegen_C_WhileActive");
static_assert(sizeof(GC_HealthRegen_C_WhileActive) == 0x000170, "Wrong size on GC_HealthRegen_C_WhileActive");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, MyTarget) == 0x000000, "Member 'GC_HealthRegen_C_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, Parameters) == 0x000008, "Member 'GC_HealthRegen_C_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, ReturnValue) == 0x0000E0, "Member 'GC_HealthRegen_C_WhileActive::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_AsBP_Char_Player) == 0x0000E8, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_AsBP_Char_Player' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_bSuccess) == 0x0000F0, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_AsVal_Character) == 0x0000F8, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_AsVal_Character' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_bSuccess_1) == 0x000100, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_GetMesh1P_ReturnValue) == 0x000108, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_GetMesh1P_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_GetMesh3P_ReturnValue) == 0x000110, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_GetMesh3P_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_GetPlayerController_ReturnValue) == 0x000118, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_AsVal_Player_Controller) == 0x000120, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_AsVal_Player_Controller' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_DynamicCast_bSuccess_2) == 0x000128, "Member 'GC_HealthRegen_C_WhileActive::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_CreateDelegate_OutputDelegate) == 0x00012C, "Member 'GC_HealthRegen_C_WhileActive::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, K2Node_CreateDelegate_OutputDelegate_1) == 0x00013C, "Member 'GC_HealthRegen_C_WhileActive::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_Create_1P3P_VFX_Active_1PVFX) == 0x000150, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_Create_1P3P_VFX_Active_1PVFX' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_Create_1P3P_VFX_1P_System_Ref) == 0x000158, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_Create_1P3P_VFX_1P_System_Ref' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_Create_1P3P_VFX_Active_3PVFX) == 0x000160, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_Create_1P3P_VFX_Active_3PVFX' has a wrong offset!");
static_assert(offsetof(GC_HealthRegen_C_WhileActive, CallFunc_Create_1P3P_VFX_3P_System_Ref) == 0x000168, "Member 'GC_HealthRegen_C_WhileActive::CallFunc_Create_1P3P_VFX_3P_System_Ref' has a wrong offset!");

}

