#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SD_Door_02

#include "Basic.hpp"


namespace SDK::Params
{

// Function SD_Door_02.SD_Door_02_C.ExecuteUbergraph_SD_Door_02
// 0x0008 (0x0008 - 0x0000)
struct SD_Door_02_C_ExecuteUbergraph_SD_Door_02 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SD_Door_02_C_ExecuteUbergraph_SD_Door_02) == 0x000004, "Wrong alignment on SD_Door_02_C_ExecuteUbergraph_SD_Door_02");
static_assert(sizeof(SD_Door_02_C_ExecuteUbergraph_SD_Door_02) == 0x000008, "Wrong size on SD_Door_02_C_ExecuteUbergraph_SD_Door_02");
static_assert(offsetof(SD_Door_02_C_ExecuteUbergraph_SD_Door_02, EntryPoint) == 0x000000, "Member 'SD_Door_02_C_ExecuteUbergraph_SD_Door_02::EntryPoint' has a wrong offset!");
static_assert(offsetof(SD_Door_02_C_ExecuteUbergraph_SD_Door_02, CallFunc_HasAuthority_ReturnValue) == 0x000004, "Member 'SD_Door_02_C_ExecuteUbergraph_SD_Door_02::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");

}

