#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StartMenuButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RallyHereStart_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass StartMenuButton.StartMenuButton_C
// 0x0030 (0x0598 - 0x0568)
class UStartMenuButton_C final : public URHContextBarPrompt
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0568(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Hovered;                                           // 0x0570(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               Button;                                            // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ContentWrapper;                                    // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                HitTarget;                                         // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__HitTarget_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__HitTarget_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__HitTarget_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void ExecuteUbergraph_StartMenuButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StartMenuButton_C">();
	}
	static class UStartMenuButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStartMenuButton_C>();
	}
};
static_assert(alignof(UStartMenuButton_C) == 0x000008, "Wrong alignment on UStartMenuButton_C");
static_assert(sizeof(UStartMenuButton_C) == 0x000598, "Wrong size on UStartMenuButton_C");
static_assert(offsetof(UStartMenuButton_C, UberGraphFrame) == 0x000568, "Member 'UStartMenuButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UStartMenuButton_C, Hovered) == 0x000570, "Member 'UStartMenuButton_C::Hovered' has a wrong offset!");
static_assert(offsetof(UStartMenuButton_C, Button) == 0x000578, "Member 'UStartMenuButton_C::Button' has a wrong offset!");
static_assert(offsetof(UStartMenuButton_C, ContentWrapper) == 0x000580, "Member 'UStartMenuButton_C::ContentWrapper' has a wrong offset!");
static_assert(offsetof(UStartMenuButton_C, HitTarget) == 0x000588, "Member 'UStartMenuButton_C::HitTarget' has a wrong offset!");
static_assert(offsetof(UStartMenuButton_C, Icon) == 0x000590, "Member 'UStartMenuButton_C::Icon' has a wrong offset!");

}

