#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STT_GetAnimationLength

#include "Basic.hpp"

#include "STT_GetAnimationLength_classes.hpp"
#include "STT_GetAnimationLength_parameters.hpp"


namespace SDK
{

// Function STT_GetAnimationLength.STT_GetAnimationLength_C.ExecuteUbergraph_STT_GetAnimationLength
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USTT_GetAnimationLength_C::ExecuteUbergraph_STT_GetAnimationLength(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_GetAnimationLength_C", "ExecuteUbergraph_STT_GetAnimationLength");

	Params::STT_GetAnimationLength_C_ExecuteUbergraph_STT_GetAnimationLength Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function STT_GetAnimationLength.STT_GetAnimationLength_C.ReceiveLatentEnterState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FStateTreeTransitionResult       Transition                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USTT_GetAnimationLength_C::ReceiveLatentEnterState(const struct FStateTreeTransitionResult& Transition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_GetAnimationLength_C", "ReceiveLatentEnterState");

	Params::STT_GetAnimationLength_C_ReceiveLatentEnterState Parms{};

	Parms.Transition = std::move(Transition);

	UObject::ProcessEvent(Func, &Parms);
}

}

