#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STT_NotifyAIState

#include "Basic.hpp"

#include "STT_NotifyAIState_classes.hpp"
#include "STT_NotifyAIState_parameters.hpp"


namespace SDK
{

// Function STT_NotifyAIState.STT_NotifyAIState_C.ExecuteUbergraph_STT_NotifyAIState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USTT_NotifyAIState_C::ExecuteUbergraph_STT_NotifyAIState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_NotifyAIState_C", "ExecuteUbergraph_STT_NotifyAIState");

	Params::STT_NotifyAIState_C_ExecuteUbergraph_STT_NotifyAIState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function STT_NotifyAIState.STT_NotifyAIState_C.ReceiveLatentEnterState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FStateTreeTransitionResult       Transition                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USTT_NotifyAIState_C::ReceiveLatentEnterState(const struct FStateTreeTransitionResult& Transition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_NotifyAIState_C", "ReceiveLatentEnterState");

	Params::STT_NotifyAIState_C_ReceiveLatentEnterState Parms{};

	Parms.Transition = std::move(Transition);

	UObject::ProcessEvent(Func, &Parms);
}

}

