#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GamepadCursor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "RallyHereAPI_structs.hpp"


namespace SDK::Params
{

// Function UI_GamepadCursor.UI_GamepadCursor_C.ExecuteUbergraph_UI_GamepadCursor
// 0x0030 (0x0030 - 0x0000)
struct UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ARHHUDCommon*                           CallFunc_GetHUDCommon_HUD_Common;                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ERHAPI_Platform                               CallFunc_GetLocalPlayerPlatformId_ReturnValue;     // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ARHHUDCommon*                           CallFunc_GetHUDCommon_HUD_Common_1;                // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor) == 0x000008, "Wrong alignment on UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor");
static_assert(sizeof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor) == 0x000030, "Wrong size on UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, EntryPoint) == 0x000000, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, CallFunc_GetHUDCommon_HUD_Common) == 0x000008, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::CallFunc_GetHUDCommon_HUD_Common' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, CallFunc_GetLocalPlayerPlatformId_ReturnValue) == 0x000010, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::CallFunc_GetLocalPlayerPlatformId_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000011, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, CallFunc_GetHUDCommon_HUD_Common_1) == 0x000018, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::CallFunc_GetHUDCommon_HUD_Common_1' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'UI_GamepadCursor_C_ExecuteUbergraph_UI_GamepadCursor::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

// Function UI_GamepadCursor.UI_GamepadCursor_C.OnViewportResized
// 0x0028 (0x0028 - 0x0000)
struct UI_GamepadCursor_C_OnViewportResized final
{
public:
	float                                         CallFunc_GetViewportScale_ReturnValue;             // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector2D_X_ImplicitCast;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector2D_Y_ImplicitCast;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_GamepadCursor_C_OnViewportResized) == 0x000008, "Wrong alignment on UI_GamepadCursor_C_OnViewportResized");
static_assert(sizeof(UI_GamepadCursor_C_OnViewportResized) == 0x000028, "Wrong size on UI_GamepadCursor_C_OnViewportResized");
static_assert(offsetof(UI_GamepadCursor_C_OnViewportResized, CallFunc_GetViewportScale_ReturnValue) == 0x000000, "Member 'UI_GamepadCursor_C_OnViewportResized::CallFunc_GetViewportScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_OnViewportResized, CallFunc_MakeVector2D_ReturnValue) == 0x000008, "Member 'UI_GamepadCursor_C_OnViewportResized::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_OnViewportResized, CallFunc_MakeVector2D_X_ImplicitCast) == 0x000018, "Member 'UI_GamepadCursor_C_OnViewportResized::CallFunc_MakeVector2D_X_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_GamepadCursor_C_OnViewportResized, CallFunc_MakeVector2D_Y_ImplicitCast) == 0x000020, "Member 'UI_GamepadCursor_C_OnViewportResized::CallFunc_MakeVector2D_Y_ImplicitCast' has a wrong offset!");

}

