#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Tooltip_Equipment_Stats

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Valhalla_structs.hpp"


namespace SDK::Params
{

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.CompareStats
// 0x0088 (0x0088 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_CompareStats final
{
public:
	class UUI_Tooltip_Equipment_Stats_C*          Stats_to_Compare;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bNoItemEquipped;                                   // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUI_City_Armory_Details_Stat_C*         K2Node_DynamicCast_AsUI_City_Armory_Details_Stat;  // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23[0x1];                                       // 0x0023(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        CallFunc_GetCachedArray_ReturnValue;               // 0x0040(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_City_Armory_Details_Stat_C*         K2Node_DynamicCast_AsUI_City_Armory_Details_Stat_1; // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast; // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GreaterEqual_DoubleDouble_B_ImplicitCast; // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_CompareStats) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_CompareStats");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_CompareStats) == 0x000088, "Wrong size on UI_Tooltip_Equipment_Stats_C_CompareStats");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, Stats_to_Compare) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::Stats_to_Compare' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, bNoItemEquipped) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::bNoItemEquipped' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_IsValid_ReturnValue) == 0x000009, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GetChildAt_ReturnValue) == 0x000010, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, K2Node_DynamicCast_AsUI_City_Armory_Details_Stat) == 0x000018, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::K2Node_DynamicCast_AsUI_City_Armory_Details_Stat' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000021, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_BooleanOR_ReturnValue) == 0x000022, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GetAllChildren_ReturnValue) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GetCachedArray_ReturnValue) == 0x000040, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GetCachedArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_Array_Get_Item) == 0x000058, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, K2Node_DynamicCast_AsUI_City_Armory_Details_Stat_1) == 0x000068, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::K2Node_DynamicCast_AsUI_City_Armory_Details_Stat_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, K2Node_DynamicCast_bSuccess_1) == 0x000070, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast) == 0x000078, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_CompareStats, CallFunc_GreaterEqual_DoubleDouble_B_ImplicitCast) == 0x000080, "Member 'UI_Tooltip_Equipment_Stats_C_CompareStats::CallFunc_GreaterEqual_DoubleDouble_B_ImplicitCast' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.ExecuteUbergraph_UI_Tooltip_Equipment_Stats
// 0x0038 (0x0038 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded;                         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsGameplay_Effect;         // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats) == 0x000038, "Wrong size on UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, EntryPoint) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, K2Node_CustomEvent_Loaded) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, Temp_class_Variable) == 0x000020, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, K2Node_ClassDynamicCast_AsGameplay_Effect) == 0x000028, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::K2Node_ClassDynamicCast_AsGameplay_Effect' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats, K2Node_ClassDynamicCast_bSuccess) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_ExecuteUbergraph_UI_Tooltip_Equipment_Stats::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.GetEffectIcon
// 0x0068 (0x0068 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_GetEffectIcon final
{
public:
	struct FGameplayTag                           EffectTag;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              Icon;                                              // 0x0008(0x0028)(Parm, OutParm, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_OutIcon;                          // 0x0038(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_GetIcon_ReturnValue;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_GetEffectIcon");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon) == 0x000068, "Wrong size on UI_Tooltip_Equipment_Stats_C_GetEffectIcon");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon, EffectTag) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_GetEffectIcon::EffectTag' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon, Icon) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_GetEffectIcon::Icon' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_GetEffectIcon::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon, CallFunc_GetIcon_OutIcon) == 0x000038, "Member 'UI_Tooltip_Equipment_Stats_C_GetEffectIcon::CallFunc_GetIcon_OutIcon' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetEffectIcon, CallFunc_GetIcon_ReturnValue) == 0x000060, "Member 'UI_Tooltip_Equipment_Stats_C_GetEffectIcon::CallFunc_GetIcon_ReturnValue' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.GetModifiers
// 0x0BA0 (0x0BA0 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_GetModifiers final
{
public:
	const class UValItemAsset*                    ItemAsset;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayModifierInfo>          Modifiers;                                         // 0x0008(0x0010)(Parm, OutParm)
	class UClass*                                 LocalAbilityClass;                                 // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayModifierInfo>          Temp_struct_Variable;                              // 0x0020(0x0010)(ReferenceParm)
	class UClass*                                 K2Node_ClassDynamicCast_AsGA_Grenade_New;          // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x003C(0x0008)(ConstParm, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SafeDivide_ReturnValue;                   // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         K2Node_MakeStruct_ScalableFloat;                   // 0x0068(0x0028)()
	struct FScalableFloat                         K2Node_MakeStruct_ScalableFloat_1;                 // 0x0090(0x0028)()
	struct FGameplayEffectModifierMagnitude       K2Node_MakeStruct_GameplayEffectModifierMagnitude; // 0x00B8(0x01E0)()
	struct FGameplayEffectModifierMagnitude       K2Node_MakeStruct_GameplayEffectModifierMagnitude_1; // 0x0298(0x01E0)()
	struct FGameplayModifierInfo                  K2Node_MakeStruct_GameplayModifierInfo;            // 0x0478(0x0338)()
	struct FGameplayModifierInfo                  K2Node_MakeStruct_GameplayModifierInfo_1;          // 0x07B0(0x0338)()
	TArray<struct FGameplayModifierInfo>          K2Node_MakeArray_Array;                            // 0x0AE8(0x0010)(ReferenceParm)
	TMap<struct FGameplayTag, struct FValGameplayEffectContainer> Temp_struct_Variable_2;                            // 0x0AF8(0x0050)()
	class UValAbilityAsset*                       K2Node_DynamicCast_AsVal_Ability_Asset;            // 0x0B48(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0B50(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B51[0x7];                                      // 0x0B51(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsVal_Gameplay_Ability;    // 0x0B58(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0B60(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_GameplayTag_ReturnValue;       // 0x0B61(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B62[0x6];                                      // 0x0B62(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FValGameplayEffectContainer            CallFunc_Map_Find_Value;                           // 0x0B68(0x0018)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0B80(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B81[0x7];                                      // 0x0B81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Array_Get_Item;                           // 0x0B88(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0B90(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B91[0x3];                                      // 0x0B91(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_MakeStruct_Value_ImplicitCast;              // 0x0B94(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Value_ImplicitCast_1;            // 0x0B98(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_GetModifiers) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_GetModifiers");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_GetModifiers) == 0x000BA0, "Wrong size on UI_Tooltip_Equipment_Stats_C_GetModifiers");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, ItemAsset) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::ItemAsset' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, Modifiers) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::Modifiers' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, LocalAbilityClass) == 0x000018, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::LocalAbilityClass' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, Temp_struct_Variable) == 0x000020, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_ClassDynamicCast_AsGA_Grenade_New) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_ClassDynamicCast_AsGA_Grenade_New' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_ClassDynamicCast_bSuccess) == 0x000038, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, Temp_struct_Variable_1) == 0x00003C, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000048, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000050, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_SelectFloat_ReturnValue) == 0x000058, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_SafeDivide_ReturnValue) == 0x000060, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_SafeDivide_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_ScalableFloat) == 0x000068, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_ScalableFloat' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_ScalableFloat_1) == 0x000090, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_ScalableFloat_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_GameplayEffectModifierMagnitude) == 0x0000B8, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_GameplayEffectModifierMagnitude' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_GameplayEffectModifierMagnitude_1) == 0x000298, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_GameplayEffectModifierMagnitude_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_GameplayModifierInfo) == 0x000478, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_GameplayModifierInfo' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_GameplayModifierInfo_1) == 0x0007B0, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_GameplayModifierInfo_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeArray_Array) == 0x000AE8, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, Temp_struct_Variable_2) == 0x000AF8, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_DynamicCast_AsVal_Ability_Asset) == 0x000B48, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_DynamicCast_AsVal_Ability_Asset' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_DynamicCast_bSuccess) == 0x000B50, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_ClassDynamicCast_AsVal_Gameplay_Ability) == 0x000B58, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_ClassDynamicCast_AsVal_Gameplay_Ability' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_ClassDynamicCast_bSuccess_1) == 0x000B60, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_EqualEqual_GameplayTag_ReturnValue) == 0x000B61, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_EqualEqual_GameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Map_Find_Value) == 0x000B68, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Map_Find_ReturnValue) == 0x000B80, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Array_Get_Item) == 0x000B88, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000B90, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_Value_ImplicitCast) == 0x000B94, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_GetModifiers, K2Node_MakeStruct_Value_ImplicitCast_1) == 0x000B98, "Member 'UI_Tooltip_Equipment_Stats_C_GetModifiers::K2Node_MakeStruct_Value_ImplicitCast_1' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC
// 0x0008 (0x0008 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC) == 0x000008, "Wrong size on UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC, Loaded) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_OnLoaded_4EF913DA4B768FC8B2092D865BEC6FCC::Loaded' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.OnPlayerDefaultAttributesClassAvailable
// 0x0368 (0x0368 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayModifierInfo>          Temp_struct_Variable;                              // 0x0010(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayModifierInfo                  CallFunc_Array_Get_Item;                           // 0x0028(0x0338)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0361(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_GameplayAttributeGameplayAttribute_ReturnValue; // 0x0362(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable) == 0x000368, "Wrong size on UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, Temp_bool_True_if_break_was_hit_Variable) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, Temp_int_Array_Index_Variable) == 0x000004, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_Not_PreBool_ReturnValue) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, Temp_struct_Variable) == 0x000010, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_Array_Length_ReturnValue) == 0x000024, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_Array_Get_Item) == 0x000028, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_Less_IntInt_ReturnValue) == 0x000360, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_BooleanAND_ReturnValue) == 0x000361, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable, CallFunc_EqualEqual_GameplayAttributeGameplayAttribute_ReturnValue) == 0x000362, "Member 'UI_Tooltip_Equipment_Stats_C_OnPlayerDefaultAttributesClassAvailable::CallFunc_EqualEqual_GameplayAttributeGameplayAttribute_ReturnValue' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_PreConstruct");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_PreConstruct) == 0x000001, "Wrong size on UI_Tooltip_Equipment_Stats_C_PreConstruct");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.Update Armor Stats
// 0x0068 (0x0068 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        CallFunc_GetCachedArray_ReturnValue;               // 0x0020(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0040(0x0010)()
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_DoubleToText_Value_ImplicitCast;     // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats) == 0x000068, "Wrong size on UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, Value) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, Temp_int_Array_Index_Variable) == 0x000004, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_GetAllChildren_ReturnValue) == 0x000010, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_GetCachedArray_ReturnValue) == 0x000020, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_GetCachedArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Array_Get_Item) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Conv_DoubleToText_ReturnValue) == 0x000040, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Conv_DoubleToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000050, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Conv_DoubleToText_Value_ImplicitCast) == 0x000058, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Conv_DoubleToText_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000060, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Armor_Stats::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.Update Weapon Stats
// 0x0100 (0x0100 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              LocalIcon;                                         // 0x0008(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FGameplayModifierInfo>          LocalModifiers;                                    // 0x0030(0x0010)(Edit, BlueprintVisible)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AValCharacter*                          CallFunc_GetCharacter_ReturnValue;                 // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           CallFunc_GetDamageTypeForItem_OutDamageType;       // 0x006C(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDamageTypeForItem_ReturnValue;         // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_75[0x3];                                       // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetEffectIcon_Icon;                       // 0x0078(0x0028)(HasGetValueTypeHash)
	TArray<struct FGameplayModifierInfo>          CallFunc_GetModifiers_Modifiers;                   // 0x00A0(0x0010)(ReferenceParm)
	bool                                          CallFunc_MatchesAnyTags_ReturnValue;               // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x00B8(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        CallFunc_GetCachedArray_ReturnValue;               // 0x00C8(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_City_Armory_Details_Stat_C*         K2Node_DynamicCast_AsUI_City_Armory_Details_Stat;  // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MatchesAnyTags_ReturnValue_1;             // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats) == 0x000100, "Wrong size on UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, Value) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, LocalIcon) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::LocalIcon' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, LocalModifiers) == 0x000030, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::LocalModifiers' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, Temp_int_Loop_Counter_Variable) == 0x000040, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetCharacter_ReturnValue) == 0x000048, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_Add_IntInt_ReturnValue) == 0x000050, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, Temp_int_Array_Index_Variable) == 0x000054, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000058, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, K2Node_DynamicCast_AsTexture_2D) == 0x000060, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetDamageTypeForItem_OutDamageType) == 0x00006C, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetDamageTypeForItem_OutDamageType' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetDamageTypeForItem_ReturnValue) == 0x000074, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetDamageTypeForItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetEffectIcon_Icon) == 0x000078, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetEffectIcon_Icon' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetModifiers_Modifiers) == 0x0000A0, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetModifiers_Modifiers' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_MatchesAnyTags_ReturnValue) == 0x0000B0, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_MatchesAnyTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x0000B1, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetAllChildren_ReturnValue) == 0x0000B8, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_GetCachedArray_ReturnValue) == 0x0000C8, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_GetCachedArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_Array_Length_ReturnValue) == 0x0000D8, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_Array_Get_Item) == 0x0000E0, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_Less_IntInt_ReturnValue) == 0x0000E8, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, K2Node_DynamicCast_AsUI_City_Armory_Details_Stat) == 0x0000F0, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::K2Node_DynamicCast_AsUI_City_Armory_Details_Stat' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, K2Node_DynamicCast_bSuccess_1) == 0x0000F8, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats, CallFunc_MatchesAnyTags_ReturnValue_1) == 0x0000F9, "Member 'UI_Tooltip_Equipment_Stats_C_Update_Weapon_Stats::CallFunc_MatchesAnyTags_ReturnValue_1' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.UpdateArmorComparison
// 0x0010 (0x0010 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison final
{
public:
	bool                                          bCompare;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsIncreasing;                                     // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select_Default;                             // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison) == 0x000010, "Wrong size on UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison, bCompare) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison::bCompare' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison, bIsIncreasing) == 0x000001, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison::bIsIncreasing' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison, Temp_bool_Variable) == 0x000002, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison, K2Node_Select_Default) == 0x000008, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateArmorComparison::K2Node_Select_Default' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.UpdateItem
// 0x0100 (0x0100 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_UpdateItem final
{
public:
	struct FInventoryItem                         InventoryItem;                                     // 0x0000(0x00D8)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          Value;                                             // 0x00D8(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UValItemAsset*                    CallFunc_GetItemAssetById_ReturnValue;             // 0x00E0(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Update_Armor_Stats_Value;                 // 0x00EA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Update_Weapon_Stats_Value;                // 0x00EB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select_Default;                             // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_UpdateItem) == 0x000008, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_UpdateItem");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_UpdateItem) == 0x000100, "Wrong size on UI_Tooltip_Equipment_Stats_C_UpdateItem");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, InventoryItem) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::InventoryItem' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, Value) == 0x0000D8, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, CallFunc_GetItemAssetById_ReturnValue) == 0x0000E0, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::CallFunc_GetItemAssetById_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, CallFunc_IsValid_ReturnValue) == 0x0000E8, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, Temp_bool_Variable) == 0x0000E9, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, CallFunc_Update_Armor_Stats_Value) == 0x0000EA, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::CallFunc_Update_Armor_Stats_Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, CallFunc_Update_Weapon_Stats_Value) == 0x0000EB, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::CallFunc_Update_Weapon_Stats_Value' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, K2Node_Select_Default) == 0x0000F0, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateItem, CallFunc_BooleanOR_ReturnValue) == 0x0000F8, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateItem::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function UI_Tooltip_Equipment_Stats.UI_Tooltip_Equipment_Stats_C.UpdateWeaponStatVisibility
// 0x0001 (0x0001 - 0x0000)
struct UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility final
{
public:
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility) == 0x000001, "Wrong alignment on UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility");
static_assert(sizeof(UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility) == 0x000001, "Wrong size on UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility");
static_assert(offsetof(UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000000, "Member 'UI_Tooltip_Equipment_Stats_C_UpdateWeaponStatVisibility::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");

}

