#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tab_Hex

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.UpdateText
// 0x0020 (0x0020 - 0x0000)
struct WBP_Tab_Hex_C_UpdateText final
{
public:
	class FText                                   Text_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0010(0x0010)()
};
static_assert(alignof(WBP_Tab_Hex_C_UpdateText) == 0x000008, "Wrong alignment on WBP_Tab_Hex_C_UpdateText");
static_assert(sizeof(WBP_Tab_Hex_C_UpdateText) == 0x000020, "Wrong size on WBP_Tab_Hex_C_UpdateText");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateText, Text_0) == 0x000000, "Member 'WBP_Tab_Hex_C_UpdateText::Text_0' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateText, CallFunc_TextToUpper_ReturnValue) == 0x000010, "Member 'WBP_Tab_Hex_C_UpdateText::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.UpdateIsEven
// 0x0020 (0x0020 - 0x0000)
struct WBP_Tab_Hex_C_UpdateIsEven final
{
public:
	bool                                          bIsEven_0;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_UpdateIsEven) == 0x000008, "Wrong alignment on WBP_Tab_Hex_C_UpdateIsEven");
static_assert(sizeof(WBP_Tab_Hex_C_UpdateIsEven) == 0x000020, "Wrong size on WBP_Tab_Hex_C_UpdateIsEven");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIsEven, bIsEven_0) == 0x000000, "Member 'WBP_Tab_Hex_C_UpdateIsEven::bIsEven_0' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIsEven, CallFunc_SelectFloat_ReturnValue) == 0x000008, "Member 'WBP_Tab_Hex_C_UpdateIsEven::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIsEven, CallFunc_MakeVector2D_ReturnValue) == 0x000010, "Member 'WBP_Tab_Hex_C_UpdateIsEven::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.UpdateIndex
// 0x000C (0x000C - 0x0000)
struct WBP_Tab_Hex_C_UpdateIndex final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_UpdateIndex) == 0x000004, "Wrong alignment on WBP_Tab_Hex_C_UpdateIndex");
static_assert(sizeof(WBP_Tab_Hex_C_UpdateIndex) == 0x00000C, "Wrong size on WBP_Tab_Hex_C_UpdateIndex");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIndex, Index_0) == 0x000000, "Member 'WBP_Tab_Hex_C_UpdateIndex::Index_0' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIndex, CallFunc_Percent_IntInt_ReturnValue) == 0x000004, "Member 'WBP_Tab_Hex_C_UpdateIndex::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateIndex, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000008, "Member 'WBP_Tab_Hex_C_UpdateIndex::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.UpdateCTA
// 0x0001 (0x0001 - 0x0000)
struct WBP_Tab_Hex_C_UpdateCTA final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_UpdateCTA) == 0x000001, "Wrong alignment on WBP_Tab_Hex_C_UpdateCTA");
static_assert(sizeof(WBP_Tab_Hex_C_UpdateCTA) == 0x000001, "Wrong size on WBP_Tab_Hex_C_UpdateCTA");
static_assert(offsetof(WBP_Tab_Hex_C_UpdateCTA, Visible) == 0x000000, "Member 'WBP_Tab_Hex_C_UpdateCTA::Visible' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Tab_Hex_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_Tab_Hex_C_PreConstruct");
static_assert(sizeof(WBP_Tab_Hex_C_PreConstruct) == 0x000001, "Wrong size on WBP_Tab_Hex_C_PreConstruct");
static_assert(offsetof(WBP_Tab_Hex_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_Tab_Hex_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.OnSelectedChanged
// 0x0050 (0x0050 - 0x0000)
struct WBP_Tab_Hex_C_OnSelectedChanged final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0004(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0018(0x0014)()
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_Select_Default;                             // 0x0038(0x0014)()
	float                                         CallFunc_SetRenderOpacity_InOpacity_ImplicitCast;  // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_OnSelectedChanged) == 0x000008, "Wrong alignment on WBP_Tab_Hex_C_OnSelectedChanged");
static_assert(sizeof(WBP_Tab_Hex_C_OnSelectedChanged) == 0x000050, "Wrong size on WBP_Tab_Hex_C_OnSelectedChanged");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, Temp_bool_Variable) == 0x000000, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, K2Node_MakeStruct_SlateColor) == 0x000004, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, K2Node_MakeStruct_SlateColor_1) == 0x000018, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, CallFunc_SelectFloat_ReturnValue) == 0x000030, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, K2Node_Select_Default) == 0x000038, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnSelectedChanged, CallFunc_SetRenderOpacity_InOpacity_ImplicitCast) == 0x00004C, "Member 'WBP_Tab_Hex_C_OnSelectedChanged::CallFunc_SetRenderOpacity_InOpacity_ImplicitCast' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.OnHoverChanged
// 0x0010 (0x0010 - 0x0000)
struct WBP_Tab_Hex_C_OnHoverChanged final
{
public:
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetRenderOpacity_InOpacity_ImplicitCast;  // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_OnHoverChanged) == 0x000008, "Wrong alignment on WBP_Tab_Hex_C_OnHoverChanged");
static_assert(sizeof(WBP_Tab_Hex_C_OnHoverChanged) == 0x000010, "Wrong size on WBP_Tab_Hex_C_OnHoverChanged");
static_assert(offsetof(WBP_Tab_Hex_C_OnHoverChanged, CallFunc_SelectFloat_ReturnValue) == 0x000000, "Member 'WBP_Tab_Hex_C_OnHoverChanged::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_OnHoverChanged, CallFunc_SetRenderOpacity_InOpacity_ImplicitCast) == 0x000008, "Member 'WBP_Tab_Hex_C_OnHoverChanged::CallFunc_SetRenderOpacity_InOpacity_ImplicitCast' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.OnDisabledChanged
// 0x0004 (0x0004 - 0x0000)
struct WBP_Tab_Hex_C_OnDisabledChanged final
{
public:
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_OnDisabledChanged) == 0x000004, "Wrong alignment on WBP_Tab_Hex_C_OnDisabledChanged");
static_assert(sizeof(WBP_Tab_Hex_C_OnDisabledChanged) == 0x000004, "Wrong size on WBP_Tab_Hex_C_OnDisabledChanged");
static_assert(offsetof(WBP_Tab_Hex_C_OnDisabledChanged, CallFunc_SelectInt_ReturnValue) == 0x000000, "Member 'WBP_Tab_Hex_C_OnDisabledChanged::CallFunc_SelectInt_ReturnValue' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.GetToolTipWidget
// 0x0028 (0x0028 - 0x0000)
struct WBP_Tab_Hex_C_GetToolTipWidget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_TooltipCommon_C*                   CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable;                              // 0x0010(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_GetToolTipWidget) == 0x000008, "Wrong alignment on WBP_Tab_Hex_C_GetToolTipWidget");
static_assert(sizeof(WBP_Tab_Hex_C_GetToolTipWidget) == 0x000028, "Wrong size on WBP_Tab_Hex_C_GetToolTipWidget");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, ReturnValue) == 0x000000, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, CallFunc_Create_ReturnValue) == 0x000008, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, Temp_struct_Variable) == 0x000010, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, CallFunc_TextIsEmpty_ReturnValue) == 0x000020, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, CallFunc_Not_PreBool_ReturnValue) == 0x000021, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_GetToolTipWidget, CallFunc_BooleanAND_ReturnValue) == 0x000022, "Member 'WBP_Tab_Hex_C_GetToolTipWidget::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function WBP_Tab_Hex.WBP_Tab_Hex_C.ExecuteUbergraph_WBP_Tab_Hex
// 0x0008 (0x0008 - 0x0000)
struct WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex) == 0x000004, "Wrong alignment on WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex");
static_assert(sizeof(WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex) == 0x000008, "Wrong size on WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex");
static_assert(offsetof(WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex, EntryPoint) == 0x000000, "Member 'WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_Tab_Hex_C_ExecuteUbergraph_WBP_Tab_Hex::K2Node_Event_IsDesignTime' has a wrong offset!");

}

