#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MatchRestartNotification

#include "Basic.hpp"

#include "WBP_MatchRestartNotification_classes.hpp"
#include "WBP_MatchRestartNotification_parameters.hpp"


namespace SDK
{

// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.UpdateTimerText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchRestartNotification_C::UpdateTimerText(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "UpdateTimerText");

	Params::WBP_MatchRestartNotification_C_UpdateTimerText Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.UpdateTimeRemaining
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MatchRestartNotification_C::UpdateTimeRemaining()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "UpdateTimeRemaining");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.OnReturnToShipTimeChanged
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MatchRestartNotification_C::OnReturnToShipTimeChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "OnReturnToShipTimeChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.OnBindingReady
// (Event, Public, BlueprintEvent)
// Parameters:
// EBindingType                            Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchRestartNotification_C::OnBindingReady(EBindingType Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "OnBindingReady");

	Params::WBP_MatchRestartNotification_C_OnBindingReady Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.Get Game State
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AValGameState_SpaceDungeon*       GameState                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bValid                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchRestartNotification_C::Get_Game_State(class AValGameState_SpaceDungeon** GameState, bool* bValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "Get Game State");

	Params::WBP_MatchRestartNotification_C_Get_Game_State Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GameState != nullptr)
		*GameState = Parms.GameState;

	if (bValid != nullptr)
		*bValid = Parms.bValid;
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.ExecuteUbergraph_WBP_MatchRestartNotification
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MatchRestartNotification_C::ExecuteUbergraph_WBP_MatchRestartNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "ExecuteUbergraph_WBP_MatchRestartNotification");

	Params::WBP_MatchRestartNotification_C_ExecuteUbergraph_WBP_MatchRestartNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MatchRestartNotification.WBP_MatchRestartNotification_C.BindGame
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MatchRestartNotification_C::BindGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MatchRestartNotification_C", "BindGame");

	UObject::ProcessEvent(Func, nullptr);
}

}

