#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LeavingMatchBlocker_RH

#include "Basic.hpp"

#include "ValhallaUI_structs.hpp"
#include "Engine_structs.hpp"
#include "Valhalla_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_LeavingMatchBlocker_RH.WBP_LeavingMatchBlocker_RH_C
// 0x0048 (0x0608 - 0x05C0)
class UWBP_LeavingMatchBlocker_RH_C final : public UValRHWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_Shared_Blocker_C*                   Blocker;                                           // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_174;                                         // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             LeavingText;                                       // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULoadingScreen_Message_C*               LoadingScreen_Message;                             // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           MainWrapper;                                       // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ModalBackground;                                   // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<struct FPromptData>                    DefaultPrompts;                                    // 0x05F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void RequestShow_1(bool Visible);
	bool RequestBack();
	void ExecuteUbergraph_WBP_LeavingMatchBlocker_RH(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_LeavingMatchBlocker_RH_C">();
	}
	static class UWBP_LeavingMatchBlocker_RH_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LeavingMatchBlocker_RH_C>();
	}
};
static_assert(alignof(UWBP_LeavingMatchBlocker_RH_C) == 0x000008, "Wrong alignment on UWBP_LeavingMatchBlocker_RH_C");
static_assert(sizeof(UWBP_LeavingMatchBlocker_RH_C) == 0x000608, "Wrong size on UWBP_LeavingMatchBlocker_RH_C");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, UberGraphFrame) == 0x0005C0, "Member 'UWBP_LeavingMatchBlocker_RH_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, Blocker) == 0x0005C8, "Member 'UWBP_LeavingMatchBlocker_RH_C::Blocker' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, Image_174) == 0x0005D0, "Member 'UWBP_LeavingMatchBlocker_RH_C::Image_174' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, LeavingText) == 0x0005D8, "Member 'UWBP_LeavingMatchBlocker_RH_C::LeavingText' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, LoadingScreen_Message) == 0x0005E0, "Member 'UWBP_LeavingMatchBlocker_RH_C::LoadingScreen_Message' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, MainWrapper) == 0x0005E8, "Member 'UWBP_LeavingMatchBlocker_RH_C::MainWrapper' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, ModalBackground) == 0x0005F0, "Member 'UWBP_LeavingMatchBlocker_RH_C::ModalBackground' has a wrong offset!");
static_assert(offsetof(UWBP_LeavingMatchBlocker_RH_C, DefaultPrompts) == 0x0005F8, "Member 'UWBP_LeavingMatchBlocker_RH_C::DefaultPrompts' has a wrong offset!");

}

