#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomKickButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CustomKickButton.WBP_CustomKickButton_C
// 0x0028 (0x02F8 - 0x02D0)
class UWBP_CustomKickButton_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Hovered;                                           // 0x02D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                KickButton;                                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnClicked;                                         // 0x02E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ForceClick();
	void ExecuteUbergraph_WBP_CustomKickButton(int32 EntryPoint);
	void BndEvt__KickButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__KickButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__KickButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CustomKickButton_C">();
	}
	static class UWBP_CustomKickButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomKickButton_C>();
	}
};
static_assert(alignof(UWBP_CustomKickButton_C) == 0x000008, "Wrong alignment on UWBP_CustomKickButton_C");
static_assert(sizeof(UWBP_CustomKickButton_C) == 0x0002F8, "Wrong size on UWBP_CustomKickButton_C");
static_assert(offsetof(UWBP_CustomKickButton_C, UberGraphFrame) == 0x0002D0, "Member 'UWBP_CustomKickButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CustomKickButton_C, Hovered) == 0x0002D8, "Member 'UWBP_CustomKickButton_C::Hovered' has a wrong offset!");
static_assert(offsetof(UWBP_CustomKickButton_C, KickButton) == 0x0002E0, "Member 'UWBP_CustomKickButton_C::KickButton' has a wrong offset!");
static_assert(offsetof(UWBP_CustomKickButton_C, OnClicked) == 0x0002E8, "Member 'UWBP_CustomKickButton_C::OnClicked' has a wrong offset!");

}

