#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomLobbyPlayer

#include "Basic.hpp"

#include "WBP_CustomLobbyPlayer_classes.hpp"
#include "WBP_CustomLobbyPlayer_parameters.hpp"


namespace SDK
{

// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.UserIsOverUs
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    IsOver                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::UserIsOverUs(bool* IsOver)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "UserIsOverUs");

	Params::WBP_CustomLobbyPlayer_C_UserIsOverUs Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsOver != nullptr)
		*IsOver = Parms.IsOver;
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.UpdateHoveredPrompts
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::UpdateHoveredPrompts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "UpdateHoveredPrompts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.SetVoiceState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldShow                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsTalking                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsMuted                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::SetVoiceState(bool ShouldShow, bool IsTalking, bool IsMuted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "SetVoiceState");

	Params::WBP_CustomLobbyPlayer_C_SetVoiceState Parms{};

	Parms.ShouldShow = ShouldShow;
	Parms.IsTalking = IsTalking;
	Parms.IsMuted = IsMuted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.SetMatchMember
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRH_CustomMatchMember            InMatchMember                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_CustomLobbyPlayer_C::SetMatchMember(const struct FRH_CustomMatchMember& InMatchMember)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "SetMatchMember");

	Params::WBP_CustomLobbyPlayer_C_SetMatchMember Parms{};

	Parms.InMatchMember = std::move(InMatchMember);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.SetEmpty
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::SetEmpty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "SetEmpty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_CustomLobbyPlayer_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "OnKeyUp");

	Params::WBP_CustomLobbyPlayer_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.OnInputStateChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ERH_INPUT_STATE                         InputState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::OnInputStateChange(ERH_INPUT_STATE InputState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "OnInputStateChange");

	Params::WBP_CustomLobbyPlayer_C_OnInputStateChange Parms{};

	Parms.InputState = InputState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.OnContextMenuOpen
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EViewSide                               side                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::OnContextMenuOpen(EViewSide side)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "OnContextMenuOpen");

	Params::WBP_CustomLobbyPlayer_C_OnContextMenuOpen Parms{};

	Parms.side = side;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.OnContextMenuClose
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::OnContextMenuClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "OnContextMenuClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.NavigateConfirm
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_CustomLobbyPlayer_C::NavigateConfirm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "NavigateConfirm");

	Params::WBP_CustomLobbyPlayer_C_NavigateConfirm Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.HandlePlayerContextUnhover
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::HandlePlayerContextUnhover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "HandlePlayerContextUnhover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.HandlePlayerContextHover
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::HandlePlayerContextHover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "HandlePlayerContextHover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.HandlePlayerClicked
// (BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::HandlePlayerClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "HandlePlayerClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.GetControlsHoverAnim
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::GetControlsHoverAnim(class UWidgetAnimation** Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "GetControlsHoverAnim");

	Params::WBP_CustomLobbyPlayer_C_GetControlsHoverAnim Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Animation != nullptr)
		*Animation = Parms.Animation;
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.GamepadUnhover
// (Event, Public, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::GamepadUnhover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "GamepadUnhover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.GamepadHover
// (Event, Public, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::GamepadHover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "GamepadHover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.ExecuteUbergraph_WBP_CustomLobbyPlayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::ExecuteUbergraph_WBP_CustomLobbyPlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "ExecuteUbergraph_WBP_CustomLobbyPlayer");

	Params::WBP_CustomLobbyPlayer_C_ExecuteUbergraph_WBP_CustomLobbyPlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.DoUnhover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayControlsHide                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::DoUnhover(bool PlayControlsHide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "DoUnhover");

	Params::WBP_CustomLobbyPlayer_C_DoUnhover Parms{};

	Parms.PlayControlsHide = PlayControlsHide;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.DoPlayerClicked
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::DoPlayerClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "DoPlayerClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.DoHover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayControlsShow                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomLobbyPlayer_C::DoHover(bool PlayControlsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "DoHover");

	Params::WBP_CustomLobbyPlayer_C_DoHover Parms{};

	Parms.PlayControlsShow = PlayControlsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__SwapButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__SwapButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__SwapButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__PlayerCardButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__LobbyPlayerButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomLobbyPlayer.WBP_CustomLobbyPlayer_C.BndEvt__KickButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_CustomLobbyPlayer_C::BndEvt__KickButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomLobbyPlayer_C", "BndEvt__KickButton_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

