#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Player_Card_Social_Entry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "RallyHereStart_structs.hpp"


namespace SDK::Params
{

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.UpdateDataItem
// 0x0050 (0x0050 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_UpdateDataItem final
{
public:
	class UObject*                                Data;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URHDataSocialPlayer*                    K2Node_DynamicCast_AsRHData_Social_Player;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URH_RHFriendAndPlatformFriend*          CallFunc_GetFriend_ReturnValue;                    // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UListViewBase*                          CallFunc_GetOwningListView_ReturnValue;            // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class URHTreeView*                            K2Node_DynamicCast_AsRHTree_View;                  // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsItemExpanded_ReturnValue;               // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class URHDataSocialCategory*                  K2Node_DynamicCast_AsRHData_Social_Category;       // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_UpdateDataItem) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_UpdateDataItem");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_UpdateDataItem) == 0x000050, "Wrong size on WBP_Player_Card_Social_Entry_C_UpdateDataItem");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, Data) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::Data' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_AsRHData_Social_Player) == 0x000008, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_AsRHData_Social_Player' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, CallFunc_GetFriend_ReturnValue) == 0x000018, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::CallFunc_GetFriend_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, CallFunc_GetOwningListView_ReturnValue) == 0x000028, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::CallFunc_GetOwningListView_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_AsRHTree_View) == 0x000030, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_AsRHTree_View' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, CallFunc_IsItemExpanded_ReturnValue) == 0x000039, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::CallFunc_IsItemExpanded_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_AsRHData_Social_Category) == 0x000040, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_AsRHData_Social_Category' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_UpdateDataItem, K2Node_DynamicCast_bSuccess_2) == 0x000048, "Member 'WBP_Player_Card_Social_Entry_C_UpdateDataItem::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.SetHoverState
// 0x0001 (0x0001 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_SetHoverState final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_SetHoverState) == 0x000001, "Wrong alignment on WBP_Player_Card_Social_Entry_C_SetHoverState");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_SetHoverState) == 0x000001, "Wrong size on WBP_Player_Card_Social_Entry_C_SetHoverState");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetHoverState, IsHovered_0) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_SetHoverState::IsHovered_0' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.SetCurrentInfoContainer
// 0x0038 (0x0038 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer final
{
public:
	class UObject*                                InfoContainer;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class URH_RHFriendAndPlatformFriend* Friend)> K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class URH_RHFriendAndPlatformFriend* Friend)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URHDataSocialPlayer*                    K2Node_DynamicCast_AsRHData_Social_Player;         // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer) == 0x000038, "Wrong size on WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, InfoContainer) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::InfoContainer' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, K2Node_DynamicCast_AsRHData_Social_Player) == 0x000028, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::K2Node_DynamicCast_AsRHData_Social_Player' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, CallFunc_IsValid_ReturnValue) == 0x000031, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer, CallFunc_IsValid_ReturnValue_1) == 0x000032, "Member 'WBP_Player_Card_Social_Entry_C_SetCurrentInfoContainer::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnRhPlayerInfoUpdated
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated final
{
public:
	class URH_RHFriendAndPlatformFriend*          Friend;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated) == 0x000008, "Wrong size on WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated, Friend) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnRhPlayerInfoUpdated::Friend' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnPlayerClicked
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnPlayerClicked final
{
public:
	class UWBP_player_card_module_C*              Selected_Player_Card;                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnPlayerClicked) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnPlayerClicked");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnPlayerClicked) == 0x000008, "Wrong size on WBP_Player_Card_Social_Entry_C_OnPlayerClicked");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnPlayerClicked, Selected_Player_Card) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnPlayerClicked::Selected_Player_Card' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnMouseLeave
// 0x0078 (0x0078 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0078)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnMouseLeave) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnMouseLeave");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnMouseLeave) == 0x000078, "Wrong size on WBP_Player_Card_Social_Entry_C_OnMouseLeave");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnMouseLeave, MouseEvent) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnMouseLeave::MouseEvent' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnMouseEnter
// 0x00B0 (0x00B0 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0078)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnMouseEnter) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnMouseEnter");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnMouseEnter) == 0x0000B0, "Wrong size on WBP_Player_Card_Social_Entry_C_OnMouseEnter");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnMouseEnter, MyGeometry) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnMouseEnter::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnMouseEnter, MouseEvent) == 0x000038, "Member 'WBP_Player_Card_Social_Entry_C_OnMouseEnter::MouseEvent' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnListItemObjectSet");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnListItemObjectSet) == 0x000008, "Wrong size on WBP_Player_Card_Social_Entry_C_OnListItemObjectSet");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.OnHeaderClicked
// 0x0008 (0x0008 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_OnHeaderClicked final
{
public:
	class UUserWidget*                            Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_OnHeaderClicked) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_OnHeaderClicked");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_OnHeaderClicked) == 0x000008, "Wrong size on WBP_Player_Card_Social_Entry_C_OnHeaderClicked");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_OnHeaderClicked, Widget) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_OnHeaderClicked::Widget' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.GetDisplayItem
// 0x0018 (0x0018 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_GetDisplayItem final
{
public:
	class URHWidget*                              ActiveDisplayItem;                                 // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_GetDisplayItem) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_GetDisplayItem");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_GetDisplayItem) == 0x000018, "Wrong size on WBP_Player_Card_Social_Entry_C_GetDisplayItem");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_GetDisplayItem, ActiveDisplayItem) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_GetDisplayItem::ActiveDisplayItem' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_GetDisplayItem, CallFunc_GetActiveWidget_ReturnValue) == 0x000008, "Member 'WBP_Player_Card_Social_Entry_C_GetDisplayItem::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_GetDisplayItem, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000010, "Member 'WBP_Player_Card_Social_Entry_C_GetDisplayItem::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.ExecuteUbergraph_WBP_Player_Card_Social_Entry
// 0x01A8 (0x01A8 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded_1;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected_1;                        // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected;                          // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserWidget* Widget)>    K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            K2Node_CustomEvent_Widget;                         // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IUserListEntry>        CallFunc_GetOwningListView_UserListEntry_CastInput; // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UListViewBase*                          CallFunc_GetOwningListView_ReturnValue;            // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsExpanded_Expanded;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTreeView*                              K2Node_DynamicCast_AsTree_View;                    // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class URHDataSocialCategory*                  CallFunc_GetData_NewParam;                         // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_player_card_module_C* Selected_Player_Card)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0060(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_player_card_module_C*              K2Node_CustomEvent_Selected_Player_Card;           // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0078(0x0038)(IsPlainOldData, NoDestructor)
	struct FPointerEvent                          K2Node_Event_MouseEvent_1;                         // 0x00B0(0x0078)(ConstParm)
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x0128(0x0078)(ConstParm)
	ERH_INPUT_STATE                               CallFunc_GetCurrentInputState_ReturnValue;         // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry) == 0x000008, "Wrong alignment on WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry) == 0x0001A8, "Wrong size on WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, EntryPoint) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_bIsExpanded_1) == 0x000004, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_bIsExpanded_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_bIsSelected_1) == 0x000005, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_bIsSelected_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_bIsSelected) == 0x000006, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_bIsExpanded) == 0x000007, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_bIsExpanded' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_ListItemObject) == 0x000008, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_CustomEvent_Widget) == 0x000020, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_CustomEvent_Widget' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_GetOwningListView_UserListEntry_CastInput) == 0x000028, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_GetOwningListView_UserListEntry_CastInput' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_GetOwningListView_ReturnValue) == 0x000038, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_GetOwningListView_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_GetIsExpanded_Expanded) == 0x000040, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_GetIsExpanded_Expanded' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_DynamicCast_AsTree_View) == 0x000048, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_DynamicCast_AsTree_View' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_Not_PreBool_ReturnValue) == 0x000051, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_GetData_NewParam) == 0x000058, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_GetData_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_CreateDelegate_OutputDelegate_1) == 0x000060, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_CustomEvent_Selected_Player_Card) == 0x000070, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_CustomEvent_Selected_Player_Card' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_MyGeometry) == 0x000078, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_MouseEvent_1) == 0x0000B0, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_MouseEvent_1' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_Event_MouseEvent) == 0x000128, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_Event_MouseEvent' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, CallFunc_GetCurrentInputState_ReturnValue) == 0x0001A0, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::CallFunc_GetCurrentInputState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry, K2Node_SwitchEnum_CmpSuccess) == 0x0001A1, "Member 'WBP_Player_Card_Social_Entry_C_ExecuteUbergraph_WBP_Player_Card_Social_Entry::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.CustomEvent_1
// 0x0001 (0x0001 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_CustomEvent_1 final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_CustomEvent_1) == 0x000001, "Wrong alignment on WBP_Player_Card_Social_Entry_C_CustomEvent_1");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_CustomEvent_1) == 0x000001, "Wrong size on WBP_Player_Card_Social_Entry_C_CustomEvent_1");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_CustomEvent_1, bIsExpanded) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_CustomEvent_1::bIsExpanded' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.CustomEvent
// 0x0001 (0x0001 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_CustomEvent final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_CustomEvent) == 0x000001, "Wrong alignment on WBP_Player_Card_Social_Entry_C_CustomEvent");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_CustomEvent) == 0x000001, "Wrong size on WBP_Player_Card_Social_Entry_C_CustomEvent");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_CustomEvent, bIsSelected) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_CustomEvent::bIsSelected' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function WBP_Player_Card_Social_Entry.WBP_Player_Card_Social_Entry_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged");
static_assert(sizeof(WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged");
static_assert(offsetof(WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'WBP_Player_Card_Social_Entry_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

}

