#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass BpPlanningMenuLibrary.BpPlanningMenuLibrary_C
class UBpPlanningMenuLibrary_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UBpPlanningMenuLibrary_C* GetDefaultObj();

	void FindIconFromItemClass(class APlayerController* Player_Controller, class UClass* ItemClass, class UObject* __WorldContext, class UTexture2D** Return_Value, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_EqualEqual_ClassClass_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue_2, bool CallFunc_EqualEqual_ClassClass_ReturnValue_3, bool CallFunc_EqualEqual_ClassClass_ReturnValue_4, bool CallFunc_EqualEqual_ClassClass_ReturnValue_5, class UWorld* CallFunc_GetWorldBP_ReturnValue, class UItemData* CallFunc_GetItemData_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_4, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue_5, const struct FArmourData& CallFunc_Array_Get_Item, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue, int32 Temp_int_Array_Index_Variable_1, const struct FDeviceData& CallFunc_Array_Get_Item_1, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, int32 Temp_int_Loop_Counter_Variable_2, const struct FDeviceData& CallFunc_Array_Get_Item_2, bool CallFunc_Less_IntInt_ReturnValue_2, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Loop_Counter_Variable_3, int32 Temp_int_Loop_Counter_Variable_4, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 Temp_int_Loop_Counter_Variable_5, bool CallFunc_Less_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_5, int32 Temp_int_Array_Index_Variable_3, int32 Temp_int_Array_Index_Variable_4, const struct FWeaponData& CallFunc_Array_Get_Item_3, const struct FArmourData& CallFunc_Array_Get_Item_4, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue_3, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue_4, int32 Temp_int_Array_Index_Variable_5, const struct FWeaponData& CallFunc_Array_Get_Item_5, class UTexture2D* CallFunc_GetLazyLoadedImage_ReturnValue_5);
	void IsFactorySkin(class UClass* SkinClass, class UObject* __WorldContext, bool* Return_Value, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue_2, bool CallFunc_EqualEqual_ClassClass_ReturnValue_3, bool CallFunc_EqualEqual_ClassClass_ReturnValue_4, bool CallFunc_EqualEqual_ClassClass_ReturnValue_5, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue_4);
	void GetCharacterDataFromHandle(class FName Handle, class UObject* __WorldContext, struct FCharacterData* Data, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UItemData* CallFunc_GetItemData_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct FCharacterData& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue);
	void PlayerStatusToText(enum class EPlayerStatus Status, class APlayerCharacter* PlayerState, class UObject* __WorldContext, class FText* StatusText, class FText Status_NotAvailable, class FText Status_Dead, class FText Status_Injured, class FText Status_Healthy, class FText Status_Ready, class FText Status_NotReady, class FText Status_None, bool K2Node_SwitchEnum_CmpSuccess, enum class EPlayerHealthStatus CallFunc_GetHealthStatus_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess_1);
	void GetAmmoDescriptionForWeaponAndAmmo(class UClass* Weapon, uint8 AmmoType, class UObject* __WorldContext, class FText* Text, class FText TaserDescription, class FText BeanbagDescription, class FText PepperballDescription, class FText SlugDescription, class FText BuckshotDescription, class FText FMJDescription, class FText JHPDescription, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue_2);
	void GetAmmoTypeNameForWeaponAndAmmo(class UClass* WeaponClass, uint8 AmmoType, class UObject* __WorldContext, class FText* Text, class FText TaserName, class FText BeanbagName, class FText PepperballName, class FText SlugName, class FText BuckshotName, class FText FMJName, class FText JHPName, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue_2);
	void GetNonDefaultLoadouts(class UObject* __WorldContext, TArray<class FString>* Loadouts, const TArray<class FString>& LoadoutNames, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class FString>& CallFunc_GetLoadoutNames_LoadoutNames, bool CallFunc_GetLoadoutNames_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const class FString& CallFunc_Array_Get_Item, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_NotEqual_StriStri_ReturnValue, bool CallFunc_NotEqual_StriStri_ReturnValue_1, bool CallFunc_NotEqual_StriStri_ReturnValue_2, bool CallFunc_NotEqual_StriStri_ReturnValue_3, bool CallFunc_NotEqual_StriStri_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_3);
	void CanCustomizeWeaponData(const struct FWeaponData& WeaponClass, class UObject* __WorldContext, bool* CanCustomize, class UDataTable* CallFunc_GetItemLookupDataTable_ReturnValue, const struct FItemLookupTable& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Greater_IntInt_ReturnValue_2, bool CallFunc_Greater_IntInt_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2);
	void CanCustomizeWeaponClass(class UClass* WeaponClass, class UObject* __WorldContext, bool* CanCustomize, class UDataTable* CallFunc_GetItemLookupDataTable_ReturnValue, const struct FItemLookupTable& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue);
	void GetArmorCoverageText(enum class EArmourCoverage Coverage, uint8 Level, class UObject* __WorldContext, class FText* Text, class FText Text_Format, class FText Text_Level3, class FText Text_Level2, class FText Text_Level1, class FText Text_FrontBackSides, class FText Text_Back, class FText Text_Front, enum class EArmourCoverage Temp_byte_Variable, class FText Temp_text_Variable, uint8 Temp_byte_Variable_1, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, class FText K2Node_Select_Default, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, class FText K2Node_Select_Default_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void GetAttachmentTextData(class UClass* Attachment, class UObject* __WorldContext, enum class ESlateVisibility* Visibility, class FText* Text, bool CallFunc_IsValidClass_ReturnValue);
	void ConstructEquipmentOverviewAmmoString(uint8 AmmoType, int32 MagazineCount, class UObject* __WorldContext, class FText* Text, class FText NoneFormat, class FText SlugFormat, class FText BuckshotFormat, class FText HPFormat, class FText FMJFormat, uint8 Temp_byte_Variable, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, class FText Temp_text_Variable_5, class FText K2Node_Select_Default, class FText CallFunc_Format_ReturnValue);
	void ItemWeightToText(float Weight, bool Fractional, class UObject* __WorldContext, class FText* Text, class FText GramsTextFormat, class FText TextFormat, class FText CallFunc_Conv_FloatToText_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, class FText CallFunc_Conv_FloatToText_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, class FText CallFunc_Conv_FloatToText_ReturnValue_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, bool Temp_bool_Variable, class FText CallFunc_Format_ReturnValue, class FText K2Node_Select_Default, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_Format_ReturnValue_1);
	void MuzzleVelocityToText(float MuzzleVelocity, class UObject* __WorldContext, class FText* Text, class FText MuzzleVelocityFormat, class FText CallFunc_Conv_FloatToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void GetCaliberFromBlueprint(TSoftClassPtr<class ABaseItem> WeaponBlueprint, class UObject* __WorldContext, class FText* CaliberText, TSubclassOf<class UObject> CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsBase_Item, bool K2Node_ClassDynamicCast_bSuccess, class UClass* K2Node_ClassDynamicCast_AsBase_Magazine_Weapon, bool K2Node_ClassDynamicCast_bSuccess_1, class FText CallFunc_Conv_StringToText_ReturnValue);
	void GetWeaponTypeLocalizedName(enum class EWeaponType WeaponType, class UObject* __WorldContext, class FText* LocalizedName, class FText UnarmedWeaponType, class FText SpecialWeaponType, class FText LessLethalPrimaryWeaponType, class FText LessLethalPistolWeaponType, class FText LethalPistolWeaponType, class FText ShotgunWeaponType, class FText SubmachineWeaponType, class FText RifleWeaponType, class FText NoWeaponType, enum class EWeaponType Temp_byte_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, class FText Temp_text_Variable_5, class FText Temp_text_Variable_6, class FText Temp_text_Variable_7, class FText Temp_text_Variable_8, class FText Temp_text_Variable_9, class FText K2Node_Select_Default);
	void GetFirstWeaponType(TArray<enum class EWeaponType>& WeaponTypes, class UObject* __WorldContext, enum class EWeaponType* WeaponType, enum class EWeaponType CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void FormatSpawnPoint(class FText SpawnPointFormat, const struct FSpawnPoints& Spawn, bool DoubleCost, class UObject* __WorldContext, class FText* Text, int32 EffectivePointsCost, class FText PointPlural, class FText PointSingular, bool Temp_bool_Variable, int32 CallFunc_Multiply_IntInt_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int32 K2Node_Select_Default, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, bool CallFunc_NotEqual_IntInt_ReturnValue, bool Temp_bool_Variable_1, class FText K2Node_Select_Default_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void GetActiveDeployablesText(class UObject* __WorldContext, class FText* Text, class AGameStateBase* CallFunc_GetGameState_ReturnValue, class ACoopGS* K2Node_DynamicCast_AsCoop_GS, bool K2Node_DynamicCast_bSuccess, TArray<int32>& CallFunc_GetEnabledDeployables_ReturnValue, class FText CallFunc_CreateOverviewDeployableListText_Text);
	void CreateOverviewDeployableListText(TArray<int32>& Deployables, class UObject* __WorldContext, class FText* Text, class FText DeployableItemFormat, class FText ReturnText, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Get_Item, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const struct FLevelDataLookupTable& CallFunc_GetLevelData_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue_1);
	void GetActivePersonnelText(class UObject* __WorldContext, class FText* Text, class AGameStateBase* CallFunc_GetGameState_ReturnValue, class ACoopGS* K2Node_DynamicCast_AsCoop_GS, bool K2Node_DynamicCast_bSuccess, TArray<int32>& CallFunc_GetEnabledPersonnel_ReturnValue, class FText CallFunc_CreateOverviewPersonnelListText_Text);
	void CreateOverviewPersonnelListText(TArray<int32>& PersonnelList, class UObject* __WorldContext, class FText* Text, class FText PersonnelItemFormat, class FText PersonnelType_Negotiator, class FText PersonnelType_PowerCrew, class FText PersonnelType_Floodlight, class FText PersonnelType_Sniper, class FText PersonnelType_Marksman, class FText PersonnelType_Spotter, class FText PersonnelType_VentilationExpert, class FText PersonnelType_Noisemaker, class FText PersonnelType_TruckDriver, class FText PersonnelType_None, class FText PersonnelTypeText, class FText PersonnelText, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, const struct FLevelDataLookupTable& CallFunc_GetLevelData_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, bool K2Node_SwitchEnum_CmpSuccess, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue);
	void GetSpawnForEntryNum(uint8 Spawn_Num, class UObject* __WorldContext, struct FSpawnPoints* Out_Spawn, const struct FLevelDataLookupTable& CallFunc_GetLevelData_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
};

}


